project_id = "slirphzzwcogdbkeicff"

[functions.create-auth-token]
verify_jwt = false

[functions.exchange-auth-token]
verify_jwt = false

[functions.ai-trip-suggestions]
verify_jwt = false

[functions.send-onboarding-email]
verify_jwt = false