/*\n  # Fix Security Issues - Foreign Key Indexes Batch 1\n  \n  This migration addresses critical performance and security issues by adding indexes to foreign key columns.\n  \n  1. **Performance Impact**\n     - Foreign key columns without indexes cause full table scans on DELETE/UPDATE operations\n     - Improves JOIN performance significantly\n     - Reduces database load and response times\n     \n  2. **Security Impact**\n     - Faster authentication and authorization checks\n     - Reduces attack surface for denial-of-service attempts\n     - Improves audit log query performance\n     \n  3. **Tables Affected (Batch 1 - 50 indexes)**\n     - ad_billing_events, ad_conversions, admin_security_alerts\n     - affiliate_events, ai_conversation_flags, ai_conversations\n     - ai_pricing_bot_suggestions, alerts, api_keys\n     - api_request_logs, audit_alerts, automation_alerts\n     - automation_events, automation_overrides, automation_safety_locks\n     - batch_stops, bill_split_payments, bill_splits\n     - blocked_entities, booking_returns, bundle_orders\n     - business_account_users, business_authorized_drivers, business_billing_alerts\n     - business_invoice_audit_log, business_trip_expenses, call_logs\n     - campaign_deliveries, car_rentals, chat_messages\n     - city_surge_rules, community_tips, conversations\n     - cost_optimization_alerts, coupon_redemptions, credit_ledger\n     - customer_feedback, customer_order_items, customer_orders\n     - delivery_batches, demand_engine_alerts, device_sessions\n     - dispute_cases, document_reminders, driver_bonus_history\n     - driver_cashouts, driver_documents, driver_earnings\n     - driver_hiring_targets, driver_incentives, driver_payouts\n*/\n\n-- Add indexes for ad_billing_events\nCREATE INDEX IF NOT EXISTS idx_ad_billing_events_click_id ON public.ad_billing_events(click_id);
\n\n-- Add indexes for ad_conversions\nCREATE INDEX IF NOT EXISTS idx_ad_conversions_click_id ON public.ad_conversions(click_id);
\n\n-- Add indexes for admin_security_alerts\nCREATE INDEX IF NOT EXISTS idx_admin_security_alerts_event_id ON public.admin_security_alerts(event_id);
\n\n-- Add indexes for affiliate_events\nCREATE INDEX IF NOT EXISTS idx_affiliate_events_affiliate_id ON public.affiliate_events(affiliate_id);
\n\n-- Add indexes for ai_conversation_flags\nCREATE INDEX IF NOT EXISTS idx_ai_conversation_flags_conversation_id ON public.ai_conversation_flags(conversation_id);
\n\n-- Add indexes for ai_conversations\nCREATE INDEX IF NOT EXISTS idx_ai_conversations_matched_faq_id ON public.ai_conversations(matched_faq_id);
\n\n-- Add indexes for ai_pricing_bot_suggestions\nCREATE INDEX IF NOT EXISTS idx_ai_pricing_bot_suggestions_run_id ON public.ai_pricing_bot_suggestions(run_id);
\n\n-- Add indexes for alerts\nCREATE INDEX IF NOT EXISTS idx_alerts_order_id ON public.alerts(order_id);
\n\n-- Add indexes for api_keys\nCREATE INDEX IF NOT EXISTS idx_api_keys_partner_id ON public.api_keys(partner_id);
\n\n-- Add indexes for api_request_logs\nCREATE INDEX IF NOT EXISTS idx_api_request_logs_api_key_id ON public.api_request_logs(api_key_id);
\n\n-- Add indexes for audit_alerts\nCREATE INDEX IF NOT EXISTS idx_audit_alerts_audit_log_id ON public.audit_alerts(audit_log_id);
\n\n-- Add indexes for automation_alerts\nCREATE INDEX IF NOT EXISTS idx_automation_alerts_source_rule_id ON public.automation_alerts(source_rule_id);
\n\n-- Add indexes for automation_events\nCREATE INDEX IF NOT EXISTS idx_automation_events_rule_id ON public.automation_events(rule_id);
\n\n-- Add indexes for automation_overrides\nCREATE INDEX IF NOT EXISTS idx_automation_overrides_target_rule_id ON public.automation_overrides(target_rule_id);
\n\n-- Add indexes for automation_safety_locks\nCREATE INDEX IF NOT EXISTS idx_automation_safety_locks_triggered_by_log_id ON public.automation_safety_locks(triggered_by_log_id);
\nCREATE INDEX IF NOT EXISTS idx_automation_safety_locks_triggered_by_rule_id ON public.automation_safety_locks(triggered_by_rule_id);
\n\n-- Add indexes for batch_stops\nCREATE INDEX IF NOT EXISTS idx_batch_stops_trip_id ON public.batch_stops(trip_id);
\n\n-- Add indexes for bill_split_payments\nCREATE INDEX IF NOT EXISTS idx_bill_split_payments_bill_split_id ON public.bill_split_payments(bill_split_id);
\n\n-- Add indexes for bill_splits\nCREATE INDEX IF NOT EXISTS idx_bill_splits_restaurant_id ON public.bill_splits(restaurant_id);
\n\n-- Add indexes for blocked_entities\nCREATE INDEX IF NOT EXISTS idx_blocked_entities_tenant_id ON public.blocked_entities(tenant_id);
\n\n-- Add indexes for booking_returns\nCREATE INDEX IF NOT EXISTS idx_booking_returns_redirect_log_id ON public.booking_returns(redirect_log_id);
\n\n-- Add indexes for bundle_orders\nCREATE INDEX IF NOT EXISTS idx_bundle_orders_bundle_id ON public.bundle_orders(bundle_id);
\n\n-- Add indexes for business_account_users\nCREATE INDEX IF NOT EXISTS idx_business_account_users_business_id ON public.business_account_users(business_id);
\n\n-- Add indexes for business_authorized_drivers\nCREATE INDEX IF NOT EXISTS idx_business_authorized_drivers_business_account_id ON public.business_authorized_drivers(business_account_id);
\n\n-- Add indexes for business_billing_alerts\nCREATE INDEX IF NOT EXISTS idx_business_billing_alerts_invoice_id ON public.business_billing_alerts(invoice_id);
\n\n-- Add indexes for business_invoice_audit_log\nCREATE INDEX IF NOT EXISTS idx_business_invoice_audit_log_invoice_id ON public.business_invoice_audit_log(invoice_id);
\n\n-- Add indexes for business_trip_expenses\nCREATE INDEX IF NOT EXISTS idx_business_trip_expenses_cost_center_id ON public.business_trip_expenses(cost_center_id);
\n\n-- Add indexes for call_logs\nCREATE INDEX IF NOT EXISTS idx_call_logs_related_driver_id ON public.call_logs(related_driver_id);
\nCREATE INDEX IF NOT EXISTS idx_call_logs_related_order_id ON public.call_logs(related_order_id);
\nCREATE INDEX IF NOT EXISTS idx_call_logs_related_restaurant_id ON public.call_logs(related_restaurant_id);
\n\n-- Add indexes for campaign_deliveries\nCREATE INDEX IF NOT EXISTS idx_campaign_deliveries_conversion_order_id ON public.campaign_deliveries(conversion_order_id);
\nCREATE INDEX IF NOT EXISTS idx_campaign_deliveries_notification_id ON public.campaign_deliveries(notification_id);
\nCREATE INDEX IF NOT EXISTS idx_campaign_deliveries_promo_code_id ON public.campaign_deliveries(promo_code_id);
\n\n-- Add indexes for car_rentals\nCREATE INDEX IF NOT EXISTS idx_car_rentals_car_id ON public.car_rentals(car_id);
\n\n-- Add indexes for chat_messages\nCREATE INDEX IF NOT EXISTS idx_chat_messages_order_id ON public.chat_messages(order_id);
\nCREATE INDEX IF NOT EXISTS idx_chat_messages_trip_id ON public.chat_messages(trip_id);
\n\n-- Add indexes for city_surge_rules\nCREATE INDEX IF NOT EXISTS idx_city_surge_rules_zone_id ON public.city_surge_rules(zone_id);
\n\n-- Add indexes for community_tips\nCREATE INDEX IF NOT EXISTS idx_community_tips_driver_id ON public.community_tips(driver_id);
\n\n-- Add indexes for conversations\nCREATE INDEX IF NOT EXISTS idx_conversations_related_order_id ON public.conversations(related_order_id);
\n\n-- Add indexes for cost_optimization_alerts\nCREATE INDEX IF NOT EXISTS idx_cost_optimization_alerts_rule_id ON public.cost_optimization_alerts(rule_id);
\n\n-- Add indexes for coupon_redemptions\nCREATE INDEX IF NOT EXISTS idx_coupon_redemptions_coupon_id ON public.coupon_redemptions(coupon_id);
\n\n-- Add indexes for credit_ledger\nCREATE INDEX IF NOT EXISTS idx_credit_ledger_referral_id ON public.credit_ledger(referral_id);
\n\n-- Add indexes for customer_feedback\nCREATE INDEX IF NOT EXISTS idx_customer_feedback_restaurant_id ON public.customer_feedback(restaurant_id);
\n\n-- Add indexes for customer_order_items\nCREATE INDEX IF NOT EXISTS idx_customer_order_items_menu_item_id ON public.customer_order_items(menu_item_id);
\n\n-- Add indexes for customer_orders\nCREATE INDEX IF NOT EXISTS idx_customer_orders_assigned_chef ON public.customer_orders(assigned_chef);
\n\n-- Add indexes for delivery_batches\nCREATE INDEX IF NOT EXISTS idx_delivery_batches_driver_id ON public.delivery_batches(driver_id);
\n\n-- Add indexes for demand_engine_alerts\nCREATE INDEX IF NOT EXISTS idx_demand_engine_alerts_zone_id ON public.demand_engine_alerts(zone_id);
\n\n-- Add indexes for device_sessions\nCREATE INDEX IF NOT EXISTS idx_device_sessions_tenant_id ON public.device_sessions(tenant_id);
\n\n-- Add indexes for dispute_cases\nCREATE INDEX IF NOT EXISTS idx_dispute_cases_order_id ON public.dispute_cases(order_id);
\n\n-- Add indexes for document_reminders\nCREATE INDEX IF NOT EXISTS idx_document_reminders_document_id ON public.document_reminders(document_id);
\n\n-- Add indexes for driver_bonus_history\nCREATE INDEX IF NOT EXISTS idx_driver_bonus_history_goal_id ON public.driver_bonus_history(goal_id);
\n\n-- Add indexes for driver_cashouts\nCREATE INDEX IF NOT EXISTS idx_driver_cashouts_driver_id ON public.driver_cashouts(driver_id);
\n\n-- Add indexes for driver_documents\nCREATE INDEX IF NOT EXISTS idx_driver_documents_driver_id ON public.driver_documents(driver_id);
\n\n-- Add indexes for driver_earnings\nCREATE INDEX IF NOT EXISTS idx_driver_earnings_trip_id ON public.driver_earnings(trip_id);
\n\n-- Add indexes for driver_hiring_targets\nCREATE INDEX IF NOT EXISTS idx_driver_hiring_targets_zone_id ON public.driver_hiring_targets(zone_id);
\n\n-- Add indexes for driver_incentives\nCREATE INDEX IF NOT EXISTS idx_driver_incentives_ai_run_id ON public.driver_incentives(ai_run_id);
\nCREATE INDEX IF NOT EXISTS idx_driver_incentives_auto_rule_id ON public.driver_incentives(auto_rule_id);
\n\n-- Add indexes for driver_payouts\nCREATE INDEX IF NOT EXISTS idx_driver_payouts_driver_id ON public.driver_payouts(driver_id);
;
