
-- ============================================================
-- Automated Cost Optimization Engine
-- ============================================================

-- 1) cost_optimization_rules — automated rules for cost control
CREATE TABLE public.cost_optimization_rules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  rule_type text NOT NULL DEFAULT 'incentive',
  condition_metric text NOT NULL,
  condition_operator text NOT NULL DEFAULT 'gt',
  condition_threshold numeric NOT NULL,
  action_type text NOT NULL DEFAULT 'alert',
  action_params jsonb NOT NULL DEFAULT '{}',
  is_enabled boolean NOT NULL DEFAULT true,
  is_auto_apply boolean NOT NULL DEFAULT false,
  last_triggered_at timestamptz,
  trigger_count int NOT NULL DEFAULT 0,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.validate_cost_opt_rule()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF NEW.rule_type NOT IN ('incentive','promotion','infrastructure','budget','margin') THEN
    RAISE EXCEPTION 'Invalid rule_type: %', NEW.rule_type;
  END IF;
  IF NEW.condition_operator NOT IN ('gt','lt','gte','lte','eq') THEN
    RAISE EXCEPTION 'Invalid condition_operator: %', NEW.condition_operator;
  END IF;
  IF NEW.action_type NOT IN ('alert','pause','adjust','limit','notify') THEN
    RAISE EXCEPTION 'Invalid action_type: %', NEW.action_type;
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_cost_opt_rule_validate
  BEFORE INSERT OR UPDATE ON public.cost_optimization_rules
  FOR EACH ROW EXECUTE FUNCTION public.validate_cost_opt_rule();

ALTER TABLE public.cost_optimization_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin full access on cost_optimization_rules"
  ON public.cost_optimization_rules FOR ALL
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

-- 2) cost_optimization_alerts — alerts generated by the engine
CREATE TABLE public.cost_optimization_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  rule_id uuid REFERENCES public.cost_optimization_rules(id) ON DELETE SET NULL,
  alert_type text NOT NULL DEFAULT 'cost_spike',
  severity text NOT NULL DEFAULT 'warning',
  title text NOT NULL,
  description text,
  metric_name text,
  metric_value numeric,
  threshold_value numeric,
  recommendation text,
  is_resolved boolean NOT NULL DEFAULT false,
  resolved_at timestamptz,
  resolved_by uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.validate_cost_opt_alert()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF NEW.alert_type NOT IN ('cost_spike','margin_decline','incentive_waste','promo_underperform','budget_exceeded','infra_cost') THEN
    RAISE EXCEPTION 'Invalid alert_type: %', NEW.alert_type;
  END IF;
  IF NEW.severity NOT IN ('info','warning','critical') THEN
    RAISE EXCEPTION 'Invalid severity: %', NEW.severity;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_cost_opt_alert_validate
  BEFORE INSERT OR UPDATE ON public.cost_optimization_alerts
  FOR EACH ROW EXECUTE FUNCTION public.validate_cost_opt_alert();

CREATE INDEX idx_cost_opt_alerts_resolved ON public.cost_optimization_alerts(is_resolved);
CREATE INDEX idx_cost_opt_alerts_type ON public.cost_optimization_alerts(alert_type);

ALTER TABLE public.cost_optimization_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admin full access on cost_optimization_alerts"
  ON public.cost_optimization_alerts FOR ALL
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));
;
