/*\n  # Add GIN Indexes for JSONB and Array Columns\n\n  1. Performance Improvements\n    - **JSONB GIN Indexes** (200+ columns)\n      - Enables fast JSON containment queries (@>, @?, @@)\n      - Optimizes JSONB property searches and filters\n      - Improves metadata, configuration, and analytics queries\n    \n    - **Array GIN Indexes** (60+ columns)\n      - Enables fast array element searches (&&, @>, <@)\n      - Optimizes permission checks, tag filtering, and multi-value queries\n      - Improves service availability and region checks\n\n  2. Index Strategy\n    - Using standard GIN operator class for maximum flexibility\n    - Supports all GIN-compatible operators\n    - Automatically maintained on INSERT/UPDATE/DELETE\n    - Trade-off: More storage for better query performance\n\n  3. Important Notes\n    - GIN indexes are larger than B-tree indexes\n    - Excellent for read-heavy workloads with containment queries\n    - Build time may be significant for large tables\n    - Updates to indexed columns are slightly slower\n    - Views are excluded (cannot create indexes on views)\n*/\n\n-- JSONB GIN Indexes - Core System Tables\nCREATE INDEX IF NOT EXISTS idx_abandoned_searches_search_params_gin ON public.abandoned_searches USING gin(search_params);
\nCREATE INDEX IF NOT EXISTS idx_achievements_reward_json_gin ON public.achievements USING gin(reward_json);
\nCREATE INDEX IF NOT EXISTS idx_activity_feed_event_data_gin ON public.activity_feed USING gin(event_data);
\nCREATE INDEX IF NOT EXISTS idx_admin_actions_payload_json_gin ON public.admin_actions USING gin(payload_json);
\nCREATE INDEX IF NOT EXISTS idx_admin_audit_logs_metadata_gin ON public.admin_audit_logs USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_admin_audit_logs_new_values_gin ON public.admin_audit_logs USING gin(new_values);
\nCREATE INDEX IF NOT EXISTS idx_admin_audit_logs_old_values_gin ON public.admin_audit_logs USING gin(old_values);
\nCREATE INDEX IF NOT EXISTS idx_admin_driver_actions_metadata_gin ON public.admin_driver_actions USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_admin_security_alerts_metadata_gin ON public.admin_security_alerts USING gin(metadata);
\n\n-- JSONB GIN Indexes - Affiliate and AI\nCREATE INDEX IF NOT EXISTS idx_affiliate_click_logs_subid_components_gin ON public.affiliate_click_logs USING gin(subid_components);
\nCREATE INDEX IF NOT EXISTS idx_ai_forecast_runs_metadata_gin ON public.ai_forecast_runs USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_ai_fraud_alerts_indicators_gin ON public.ai_fraud_alerts USING gin(indicators);
\nCREATE INDEX IF NOT EXISTS idx_ai_model_metrics_metadata_gin ON public.ai_model_metrics USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_ai_pricing_bot_runs_metadata_gin ON public.ai_pricing_bot_runs USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_ai_pricing_bot_suggestions_factors_gin ON public.ai_pricing_bot_suggestions USING gin(factors);
\nCREATE INDEX IF NOT EXISTS idx_ai_pricing_suggestions_factors_gin ON public.ai_pricing_suggestions USING gin(factors);
\nCREATE INDEX IF NOT EXISTS idx_ai_recommendations_context_gin ON public.ai_recommendations USING gin(context);
\nCREATE INDEX IF NOT EXISTS idx_ai_search_rankings_rankings_gin ON public.ai_search_rankings USING gin(rankings);
\nCREATE INDEX IF NOT EXISTS idx_ai_search_rankings_search_params_gin ON public.ai_search_rankings USING gin(search_params);
\n\n-- JSONB GIN Indexes - Analytics and Applications\nCREATE INDEX IF NOT EXISTS idx_airports_geo_polygon_gin ON public.airports USING gin(geo_polygon);
\nCREATE INDEX IF NOT EXISTS idx_analytics_events_meta_gin ON public.analytics_events USING gin(meta);
\nCREATE INDEX IF NOT EXISTS idx_analytics_funnels_steps_gin ON public.analytics_funnels USING gin(steps);
\nCREATE INDEX IF NOT EXISTS idx_app_settings_value_gin ON public.app_settings USING gin(value);
\nCREATE INDEX IF NOT EXISTS idx_application_events_meta_gin ON public.application_events USING gin(meta);
\nCREATE INDEX IF NOT EXISTS idx_applications_checklist_gin ON public.applications USING gin(checklist);
\nCREATE INDEX IF NOT EXISTS idx_audit_logs_new_values_gin ON public.audit_logs USING gin(new_values);
\nCREATE INDEX IF NOT EXISTS idx_audit_logs_old_values_gin ON public.audit_logs USING gin(old_values);
\n\n-- JSONB GIN Indexes - Automation\nCREATE INDEX IF NOT EXISTS idx_auto_operations_recommendation_gin ON public.auto_operations USING gin(recommendation);
\nCREATE INDEX IF NOT EXISTS idx_automation_alerts_metadata_gin ON public.automation_alerts USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_automation_job_runs_summary_gin ON public.automation_job_runs USING gin(summary);
\nCREATE INDEX IF NOT EXISTS idx_automation_jobs_config_gin ON public.automation_jobs USING gin(config);
\nCREATE INDEX IF NOT EXISTS idx_automation_jobs_last_run_summary_gin ON public.automation_jobs USING gin(last_run_summary);
\nCREATE INDEX IF NOT EXISTS idx_automation_logs_input_data_gin ON public.automation_logs USING gin(input_data);
\nCREATE INDEX IF NOT EXISTS idx_automation_logs_output_data_gin ON public.automation_logs USING gin(output_data);
\nCREATE INDEX IF NOT EXISTS idx_automation_rules_action_config_gin ON public.automation_rules USING gin(action_config);
\nCREATE INDEX IF NOT EXISTS idx_automation_rules_conditions_gin ON public.automation_rules USING gin(conditions);
\nCREATE INDEX IF NOT EXISTS idx_automation_rules_trigger_config_gin ON public.automation_rules USING gin(trigger_config);
\nCREATE INDEX IF NOT EXISTS idx_automation_safety_locks_metadata_gin ON public.automation_safety_locks USING gin(metadata);
\n\n-- JSONB GIN Indexes - Background and Batch\nCREATE INDEX IF NOT EXISTS idx_background_checks_raw_gin ON public.background_checks USING gin(raw);
\nCREATE INDEX IF NOT EXISTS idx_background_jobs_payload_gin ON public.background_jobs USING gin(payload);
\nCREATE INDEX IF NOT EXISTS idx_backup_logs_metadata_gin ON public.backup_logs USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_batch_events_details_gin ON public.batch_events USING gin(details);
\nCREATE INDEX IF NOT EXISTS idx_behavior_anomalies_meta_gin ON public.behavior_anomalies USING gin(meta);
\nCREATE INDEX IF NOT EXISTS idx_blocked_entities_metadata_gin ON public.blocked_entities USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_booking_audit_logs_meta_gin ON public.booking_audit_logs USING gin(meta);
\nCREATE INDEX IF NOT EXISTS idx_booking_returns_callback_params_gin ON public.booking_returns USING gin(callback_params);
\n\n-- JSONB GIN Indexes - Business\nCREATE INDEX IF NOT EXISTS idx_business_invoice_audit_log_new_values_gin ON public.business_invoice_audit_log USING gin(new_values);
\nCREATE INDEX IF NOT EXISTS idx_business_invoice_audit_log_old_values_gin ON public.business_invoice_audit_log USING gin(old_values);
\nCREATE INDEX IF NOT EXISTS idx_business_invoice_line_items_metadata_gin ON public.business_invoice_line_items USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_business_policy_audit_log_new_values_gin ON public.business_policy_audit_log USING gin(new_values);
\nCREATE INDEX IF NOT EXISTS idx_business_policy_audit_log_old_values_gin ON public.business_policy_audit_log USING gin(old_values);
\n\n-- JSONB GIN Indexes - Cart and Checklists\nCREATE INDEX IF NOT EXISTS idx_cart_items_modifiers_gin ON public.cart_items USING gin(modifiers);
\nCREATE INDEX IF NOT EXISTS idx_checklist_templates_items_gin ON public.checklist_templates USING gin(items);
\nCREATE INDEX IF NOT EXISTS idx_city_settings_services_enabled_gin ON public.city_settings USING gin(services_enabled);
\nCREATE INDEX IF NOT EXISTS idx_company_policies_allowed_services_gin ON public.company_policies USING gin(allowed_services);
\n\n-- JSONB GIN Indexes - Compliance\nCREATE INDEX IF NOT EXISTS idx_compliance_audit_logs_metadata_gin ON public.compliance_audit_logs USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_compliance_reviews_action_items_gin ON public.compliance_reviews USING gin(action_items);
\nCREATE INDEX IF NOT EXISTS idx_compliance_reviews_findings_gin ON public.compliance_reviews USING gin(findings);
\nCREATE INDEX IF NOT EXISTS idx_cost_optimization_rules_action_params_gin ON public.cost_optimization_rules USING gin(action_params);
\nCREATE INDEX IF NOT EXISTS idx_country_services_config_gin ON public.country_services USING gin(config);
\nCREATE INDEX IF NOT EXISTS idx_country_tax_config_config_gin ON public.country_tax_config USING gin(config);
\n\n-- JSONB GIN Indexes - Deliveries and Demand\nCREATE INDEX IF NOT EXISTS idx_deliveries_dropoff_location_gin ON public.deliveries USING gin(dropoff_location);
\nCREATE INDEX IF NOT EXISTS idx_deliveries_pickup_location_gin ON public.deliveries USING gin(pickup_location);
\nCREATE INDEX IF NOT EXISTS idx_demand_forecasts_metadata_gin ON public.demand_forecasts USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_dispatch_ai_logs_candidate_drivers_gin ON public.dispatch_ai_logs USING gin(candidate_drivers);
\n\n-- JSONB GIN Indexes - Disputes and DR\nCREATE INDEX IF NOT EXISTS idx_dispute_audit_logs_metadata_gin ON public.dispute_audit_logs USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_dispute_audit_logs_new_values_gin ON public.dispute_audit_logs USING gin(new_values);
\nCREATE INDEX IF NOT EXISTS idx_dispute_audit_logs_old_values_gin ON public.dispute_audit_logs USING gin(old_values);
\nCREATE INDEX IF NOT EXISTS idx_dr_active_incidents_metadata_gin ON public.dr_active_incidents USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_dr_configuration_config_value_gin ON public.dr_configuration USING gin(config_value);
\n\n-- JSONB GIN Indexes - Driver\nCREATE INDEX IF NOT EXISTS idx_driver_incentives_conditions_json_gin ON public.driver_incentives USING gin(conditions_json);
\nCREATE INDEX IF NOT EXISTS idx_driver_notification_logs_data_gin ON public.driver_notification_logs USING gin(data);
\nCREATE INDEX IF NOT EXISTS idx_driver_notifications_data_gin ON public.driver_notifications USING gin(data);
\nCREATE INDEX IF NOT EXISTS idx_driver_reposition_recommendations_metadata_gin ON public.driver_reposition_recommendations USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_driver_requirements_required_documents_gin ON public.driver_requirements USING gin(required_documents);
\nCREATE INDEX IF NOT EXISTS idx_driver_state_events_meta_gin ON public.driver_state_events USING gin(meta);
\nCREATE INDEX IF NOT EXISTS idx_driver_tiers_benefits_json_gin ON public.driver_tiers USING gin(benefits_json);
\nCREATE INDEX IF NOT EXISTS idx_driver_withdrawals_metadata_gin ON public.driver_withdrawals USING gin(metadata);
\n\n-- JSONB GIN Indexes - Eats\nCREATE INDEX IF NOT EXISTS idx_eats_zones_polygon_gin ON public.eats_zones USING gin(polygon);
\nCREATE INDEX IF NOT EXISTS idx_eats_zones_services_enabled_gin ON public.eats_zones USING gin(services_enabled);
\n\n-- JSONB GIN Indexes - Email\nCREATE INDEX IF NOT EXISTS idx_email_consents_metadata_gin ON public.email_consents USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_email_logs_metadata_gin ON public.email_logs USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_email_settings_setting_value_gin ON public.email_settings USING gin(setting_value);
\nCREATE INDEX IF NOT EXISTS idx_engagement_notifications_metadata_gin ON public.engagement_notifications USING gin(metadata);
\n\n-- JSONB GIN Indexes - Experiments\nCREATE INDEX IF NOT EXISTS idx_experiment_events_metadata_gin ON public.experiment_events USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_experiments_auto_stop_rules_gin ON public.experiments USING gin(auto_stop_rules);
\nCREATE INDEX IF NOT EXISTS idx_experiments_targeting_rules_gin ON public.experiments USING gin(targeting_rules);
\nCREATE INDEX IF NOT EXISTS idx_experiments_variants_gin ON public.experiments USING gin(variants);
\n\n-- JSONB GIN Indexes - Finance and Fleet\nCREATE INDEX IF NOT EXISTS idx_fare_calculations_breakdown_json_gin ON public.fare_calculations USING gin(breakdown_json);
\nCREATE INDEX IF NOT EXISTS idx_finance_ledger_meta_gin ON public.finance_ledger USING gin(meta);
\nCREATE INDEX IF NOT EXISTS idx_fleet_team_members_permissions_gin ON public.fleet_team_members USING gin(permissions);
\n\n-- JSONB GIN Indexes - Flight Bookings\nCREATE INDEX IF NOT EXISTS idx_flight_bookings_baggage_allowance_gin ON public.flight_bookings USING gin(baggage_allowance);
\nCREATE INDEX IF NOT EXISTS idx_flight_bookings_fare_rules_gin ON public.flight_bookings USING gin(fare_rules);
\nCREATE INDEX IF NOT EXISTS idx_flight_bookings_passengers_gin ON public.flight_bookings USING gin(passengers);
\nCREATE INDEX IF NOT EXISTS idx_flight_bookings_seat_selection_gin ON public.flight_bookings USING gin(seat_selection);
\nCREATE INDEX IF NOT EXISTS idx_flight_bookings_ticket_numbers_gin ON public.flight_bookings USING gin(ticket_numbers);
\nCREATE INDEX IF NOT EXISTS idx_flight_email_logs_metadata_gin ON public.flight_email_logs USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_flight_incident_logs_affected_booking_ids_gin ON public.flight_incident_logs USING gin(affected_booking_ids);
\nCREATE INDEX IF NOT EXISTS idx_flight_payment_audit_log_metadata_gin ON public.flight_payment_audit_log USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_flight_search_cache_offers_data_gin ON public.flight_search_cache USING gin(offers_data);
\nCREATE INDEX IF NOT EXISTS idx_flight_ticketing_logs_request_payload_gin ON public.flight_ticketing_logs USING gin(request_payload);
\nCREATE INDEX IF NOT EXISTS idx_flight_ticketing_logs_response_payload_gin ON public.flight_ticketing_logs USING gin(response_payload);
\n\n-- JSONB GIN Indexes - Food Orders\nCREATE INDEX IF NOT EXISTS idx_food_orders_delivery_stops_gin ON public.food_orders USING gin(delivery_stops);
\nCREATE INDEX IF NOT EXISTS idx_food_orders_items_gin ON public.food_orders USING gin(items);
\nCREATE INDEX IF NOT EXISTS idx_food_orders_pricing_breakdown_gin ON public.food_orders USING gin(pricing_breakdown);
\n\n-- JSONB GIN Indexes - Fraud\nCREATE INDEX IF NOT EXISTS idx_fraud_assessments_signals_gin ON public.fraud_assessments USING gin(signals);
\nCREATE INDEX IF NOT EXISTS idx_fraud_rules_condition_gin ON public.fraud_rules USING gin(condition);
\nCREATE INDEX IF NOT EXISTS idx_fraud_signals_metadata_gin ON public.fraud_signals USING gin(metadata);
\n\n-- JSONB GIN Indexes - Growth and Hotels\nCREATE INDEX IF NOT EXISTS idx_growth_actions_parameters_gin ON public.growth_actions USING gin(parameters);
\nCREATE INDEX IF NOT EXISTS idx_hotel_rooms_amenities_gin ON public.hotel_rooms USING gin(amenities);
\nCREATE INDEX IF NOT EXISTS idx_hotel_rooms_images_gin ON public.hotel_rooms USING gin(images);
\nCREATE INDEX IF NOT EXISTS idx_hotels_amenities_gin ON public.hotels USING gin(amenities);
\nCREATE INDEX IF NOT EXISTS idx_hotels_images_gin ON public.hotels USING gin(images);
\n\n-- JSONB GIN Indexes - Identity\nCREATE INDEX IF NOT EXISTS idx_identity_verifications_raw_gin ON public.identity_verifications USING gin(raw);
\n\n-- JSONB GIN Indexes - Jobs and KYC\nCREATE INDEX IF NOT EXISTS idx_job_events_meta_gin ON public.job_events USING gin(meta);
\nCREATE INDEX IF NOT EXISTS idx_kyc_events_meta_gin ON public.kyc_events USING gin(meta);
\nCREATE INDEX IF NOT EXISTS idx_kyc_events_metadata_gin ON public.kyc_events USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_kyc_submissions_data_json_gin ON public.kyc_submissions USING gin(data_json);
\nCREATE INDEX IF NOT EXISTS idx_kyc_submissions_document_urls_json_gin ON public.kyc_submissions USING gin(document_urls_json);
\nCREATE INDEX IF NOT EXISTS idx_kyc_submissions_documents_gin ON public.kyc_submissions USING gin(documents);
\nCREATE INDEX IF NOT EXISTS idx_kyc_submissions_personal_info_gin ON public.kyc_submissions USING gin(personal_info);
\n\n-- JSONB GIN Indexes - Launch Monitoring\nCREATE INDEX IF NOT EXISTS idx_launch_monitoring_alerts_details_gin ON public.launch_monitoring_alerts USING gin(details);
\nCREATE INDEX IF NOT EXISTS idx_launch_phase_log_blockers_at_start_gin ON public.launch_phase_log USING gin(blockers_at_start);
\nCREATE INDEX IF NOT EXISTS idx_launch_phase_log_metrics_snapshot_gin ON public.launch_phase_log USING gin(metrics_snapshot);
\n\n-- JSONB GIN Indexes - Ledger and Legal\nCREATE INDEX IF NOT EXISTS idx_ledger_entries_meta_gin ON public.ledger_entries USING gin(meta);
\nCREATE INDEX IF NOT EXISTS idx_legal_audit_log_metadata_gin ON public.legal_audit_log USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_loyalty_members_preferences_gin ON public.loyalty_members USING gin(preferences);
\nCREATE INDEX IF NOT EXISTS idx_loyalty_settings_value_gin ON public.loyalty_settings USING gin(value);
\nCREATE INDEX IF NOT EXISTS idx_loyalty_tiers_benefits_json_gin ON public.loyalty_tiers USING gin(benefits_json);
\n\n-- JSONB GIN Indexes - Marketing\nCREATE INDEX IF NOT EXISTS idx_marketing_campaigns_target_criteria_gin ON public.marketing_campaigns USING gin(target_criteria);
\nCREATE INDEX IF NOT EXISTS idx_marketing_campaigns_trigger_config_gin ON public.marketing_campaigns USING gin(trigger_config);
\nCREATE INDEX IF NOT EXISTS idx_menu_import_logs_errors_gin ON public.menu_import_logs USING gin(errors);
\n\n-- JSONB GIN Indexes - Notifications\nCREATE INDEX IF NOT EXISTS idx_notification_attempts_payload_gin ON public.notification_attempts USING gin(payload);
\nCREATE INDEX IF NOT EXISTS idx_notification_audit_metadata_gin ON public.notification_audit USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_notification_campaigns_action_data_gin ON public.notification_campaigns USING gin(action_data);
\nCREATE INDEX IF NOT EXISTS idx_notification_campaigns_target_filters_gin ON public.notification_campaigns USING gin(target_filters);
\nCREATE INDEX IF NOT EXISTS idx_notification_templates_variables_gin ON public.notification_templates USING gin(variables);
\nCREATE INDEX IF NOT EXISTS idx_notifications_metadata_gin ON public.notifications USING gin(metadata);
\n\n-- JSONB GIN Indexes - Offline and Operations\nCREATE INDEX IF NOT EXISTS idx_offline_sync_queue_action_data_gin ON public.offline_sync_queue USING gin(action_data);
\nCREATE INDEX IF NOT EXISTS idx_operations_checklists_items_gin ON public.operations_checklists USING gin(items);
\nCREATE INDEX IF NOT EXISTS idx_optimization_metrics_metadata_gin ON public.optimization_metrics USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_order_actions_meta_gin ON public.order_actions USING gin(meta);
\nCREATE INDEX IF NOT EXISTS idx_order_events_data_gin ON public.order_events USING gin(data);
\nCREATE INDEX IF NOT EXISTS idx_otp_codes_signup_data_gin ON public.otp_codes USING gin(signup_data);
\n\n-- JSONB GIN Indexes - P2P\nCREATE INDEX IF NOT EXISTS idx_p2p_disputes_evidence_gin ON public.p2p_disputes USING gin(evidence);
\nCREATE INDEX IF NOT EXISTS idx_p2p_enhanced_claims_partner_response_gin ON public.p2p_enhanced_claims USING gin(partner_response);
\nCREATE INDEX IF NOT EXISTS idx_p2p_protection_plans_coverage_excludes_gin ON public.p2p_protection_plans USING gin(coverage_excludes);
\nCREATE INDEX IF NOT EXISTS idx_p2p_protection_plans_coverage_includes_gin ON public.p2p_protection_plans USING gin(coverage_includes);
\nCREATE INDEX IF NOT EXISTS idx_p2p_vehicles_features_gin ON public.p2p_vehicles USING gin(features);
\nCREATE INDEX IF NOT EXISTS idx_p2p_vehicles_images_gin ON public.p2p_vehicles USING gin(images);
\n\n-- JSONB GIN Indexes - Partner\nCREATE INDEX IF NOT EXISTS idx_partner_portal_applications_documents_json_gin ON public.partner_portal_applications USING gin(documents_json);
\nCREATE INDEX IF NOT EXISTS idx_partner_redirect_logs_metadata_gin ON public.partner_redirect_logs USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_partner_redirect_logs_search_params_gin ON public.partner_redirect_logs USING gin(search_params);
\n\n-- JSONB GIN Indexes - Payment and Performance\nCREATE INDEX IF NOT EXISTS idx_payment_disputes_raw_gin ON public.payment_disputes USING gin(raw);
\nCREATE INDEX IF NOT EXISTS idx_pending_profile_changes_change_data_gin ON public.pending_profile_changes USING gin(change_data);
\nCREATE INDEX IF NOT EXISTS idx_performance_metrics_meta_gin ON public.performance_metrics USING gin(meta);
\nCREATE INDEX IF NOT EXISTS idx_performance_score_history_metrics_snapshot_gin ON public.performance_score_history USING gin(metrics_snapshot);
\nCREATE INDEX IF NOT EXISTS idx_platform_settings_value_gin ON public.platform_settings USING gin(value);
\nCREATE INDEX IF NOT EXISTS idx_points_ledger_metadata_gin ON public.points_ledger USING gin(metadata);
\n\n-- JSONB GIN Indexes - Pricing\nCREATE INDEX IF NOT EXISTS idx_price_calculations_calculation_inputs_gin ON public.price_calculations USING gin(calculation_inputs);
\nCREATE INDEX IF NOT EXISTS idx_production_test_bookings_test_details_gin ON public.production_test_bookings USING gin(test_details);
\nCREATE INDEX IF NOT EXISTS idx_provider_health_metadata_gin ON public.provider_health USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_push_notification_logs_data_gin ON public.push_notification_logs USING gin(data);
\nCREATE INDEX IF NOT EXISTS idx_push_segments_rules_json_gin ON public.push_segments USING gin(rules_json);
\n\n-- JSONB GIN Indexes - Rating and Recovery\nCREATE INDEX IF NOT EXISTS idx_rating_flags_details_gin ON public.rating_flags USING gin(details);
\nCREATE INDEX IF NOT EXISTS idx_recovery_tests_test_results_gin ON public.recovery_tests USING gin(test_results);
\nCREATE INDEX IF NOT EXISTS idx_referral_fraud_flags_details_gin ON public.referral_fraud_flags USING gin(details);
\nCREATE INDEX IF NOT EXISTS idx_referrals_fraud_flags_gin ON public.referrals USING gin(fraud_flags);
\n\n-- JSONB GIN Indexes - Region\nCREATE INDEX IF NOT EXISTS idx_region_change_logs_metadata_gin ON public.region_change_logs USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_region_settings_config_gin ON public.region_settings USING gin(config);
\nCREATE INDEX IF NOT EXISTS idx_regions_bbox_gin ON public.regions USING gin(bbox);
\nCREATE INDEX IF NOT EXISTS idx_regions_polygon_gin ON public.regions USING gin(polygon);
\n\n-- JSONB GIN Indexes - Rental Cars\nCREATE INDEX IF NOT EXISTS idx_rental_cars_features_gin ON public.rental_cars USING gin(features);
\nCREATE INDEX IF NOT EXISTS idx_rental_cars_images_gin ON public.rental_cars USING gin(images);
\n\n-- JSONB GIN Indexes - Restaurant\nCREATE INDEX IF NOT EXISTS idx_restaurant_analytics_daily_top_items_gin ON public.restaurant_analytics_daily USING gin(top_items);
\nCREATE INDEX IF NOT EXISTS idx_restaurant_branches_hours_gin ON public.restaurant_branches USING gin(hours);
\nCREATE INDEX IF NOT EXISTS idx_restaurant_status_log_new_state_gin ON public.restaurant_status_log USING gin(new_state);
\nCREATE INDEX IF NOT EXISTS idx_restaurant_status_log_previous_state_gin ON public.restaurant_status_log USING gin(previous_state);
\nCREATE INDEX IF NOT EXISTS idx_restaurant_tiers_benefits_json_gin ON public.restaurant_tiers USING gin(benefits_json);
\nCREATE INDEX IF NOT EXISTS idx_restaurants_delivery_polygon_gin ON public.restaurants USING gin(delivery_polygon);
\nCREATE INDEX IF NOT EXISTS idx_restaurants_hours_gin ON public.restaurants USING gin(hours);
\nCREATE INDEX IF NOT EXISTS idx_restaurants_opening_hours_gin ON public.restaurants USING gin(opening_hours);
\n\n-- JSONB GIN Indexes - Restricted and Rewards\nCREATE INDEX IF NOT EXISTS idx_restricted_zones_polygon_gin ON public.restricted_zones USING gin(polygon);
\nCREATE INDEX IF NOT EXISTS idx_reward_issuances_metadata_gin ON public.reward_issuances USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_reward_rules_reward_meta_gin ON public.reward_rules USING gin(reward_meta);
\nCREATE INDEX IF NOT EXISTS idx_ride_quotes_multipliers_gin ON public.ride_quotes USING gin(multipliers);
\n\n-- JSONB GIN Indexes - Risk\nCREATE INDEX IF NOT EXISTS idx_risk_events_details_gin ON public.risk_events USING gin(details);
\nCREATE INDEX IF NOT EXISTS idx_risk_flags_meta_gin ON public.risk_flags USING gin(meta);
\nCREATE INDEX IF NOT EXISTS idx_risk_scores_score_breakdown_gin ON public.risk_scores USING gin(score_breakdown);
\n\n-- JSONB GIN Indexes - Scheduled and Search\nCREATE INDEX IF NOT EXISTS idx_scheduled_bookings_details_gin ON public.scheduled_bookings USING gin(details);
\nCREATE INDEX IF NOT EXISTS idx_search_sessions_search_params_gin ON public.search_sessions USING gin(search_params);
\nCREATE INDEX IF NOT EXISTS idx_security_events_event_data_gin ON public.security_events USING gin(event_data);
\nCREATE INDEX IF NOT EXISTS idx_security_events_location_data_gin ON public.security_events USING gin(location_data);
\nCREATE INDEX IF NOT EXISTS idx_service_health_status_metadata_gin ON public.service_health_status USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_service_zones_polygon_gin ON public.service_zones USING gin(polygon);
\nCREATE INDEX IF NOT EXISTS idx_smart_sort_rules_scoring_weights_gin ON public.smart_sort_rules USING gin(scoring_weights);
\nCREATE INDEX IF NOT EXISTS idx_special_fees_condition_config_gin ON public.special_fees USING gin(condition_config);
\n\n-- JSONB GIN Indexes - Square\nCREATE INDEX IF NOT EXISTS idx_square_catalog_categories_raw_gin ON public.square_catalog_categories USING gin(raw);
\nCREATE INDEX IF NOT EXISTS idx_square_catalog_items_raw_gin ON public.square_catalog_items USING gin(raw);
\nCREATE INDEX IF NOT EXISTS idx_square_item_variations_raw_gin ON public.square_item_variations USING gin(raw);
\nCREATE INDEX IF NOT EXISTS idx_square_items_raw_gin ON public.square_items USING gin(raw);
\nCREATE INDEX IF NOT EXISTS idx_square_modifiers_raw_gin ON public.square_modifiers USING gin(raw);
\nCREATE INDEX IF NOT EXISTS idx_square_orders_raw_gin ON public.square_orders USING gin(raw);
\nCREATE INDEX IF NOT EXISTS idx_square_webhook_events_payload_gin ON public.square_webhook_events USING gin(payload);
\n\n-- JSONB GIN Indexes - Staff and State\nCREATE INDEX IF NOT EXISTS idx_staff_members_permissions_gin ON public.staff_members USING gin(permissions);
\nCREATE INDEX IF NOT EXISTS idx_state_regulatory_rules_details_gin ON public.state_regulatory_rules USING gin(details);
\nCREATE INDEX IF NOT EXISTS idx_stripe_webhook_events_payload_gin ON public.stripe_webhook_events USING gin(payload);
\nCREATE INDEX IF NOT EXISTS idx_subscription_plans_benefits_json_gin ON public.subscription_plans USING gin(benefits_json);
\nCREATE INDEX IF NOT EXISTS idx_supplier_payouts_meta_gin ON public.supplier_payouts USING gin(meta);
\n\n-- JSONB GIN Indexes - Support\nCREATE INDEX IF NOT EXISTS idx_support_metrics_tickets_by_category_gin ON public.support_metrics USING gin(tickets_by_category);
\nCREATE INDEX IF NOT EXISTS idx_support_metrics_tickets_by_priority_gin ON public.support_metrics USING gin(tickets_by_priority);
\n\n-- JSONB GIN Indexes - System\nCREATE INDEX IF NOT EXISTS idx_system_health_history_metrics_gin ON public.system_health_history USING gin(metrics);
\nCREATE INDEX IF NOT EXISTS idx_system_health_history_service_statuses_gin ON public.system_health_history USING gin(service_statuses);
\nCREATE INDEX IF NOT EXISTS idx_system_logs_meta_gin ON public.system_logs USING gin(meta);
\nCREATE INDEX IF NOT EXISTS idx_system_settings_value_gin ON public.system_settings USING gin(value);
\n\n-- JSONB GIN Indexes - Team and Tenant\nCREATE INDEX IF NOT EXISTS idx_team_role_definitions_responsibilities_gin ON public.team_role_definitions USING gin(responsibilities);
\nCREATE INDEX IF NOT EXISTS idx_team_role_definitions_sla_targets_gin ON public.team_role_definitions USING gin(sla_targets);
\nCREATE INDEX IF NOT EXISTS idx_tenant_audit_log_after_values_gin ON public.tenant_audit_log USING gin(after_values);
\nCREATE INDEX IF NOT EXISTS idx_tenant_audit_log_before_values_gin ON public.tenant_audit_log USING gin(before_values);
\nCREATE INDEX IF NOT EXISTS idx_tenant_audit_log_metadata_gin ON public.tenant_audit_log USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_tenants_settings_gin ON public.tenants USING gin(settings);
\nCREATE INDEX IF NOT EXISTS idx_ticket_events_meta_gin ON public.ticket_events USING gin(meta);
\n\n-- JSONB GIN Indexes - Training and Transactions\nCREATE INDEX IF NOT EXISTS idx_training_quiz_attempts_answers_gin ON public.training_quiz_attempts USING gin(answers);
\nCREATE INDEX IF NOT EXISTS idx_training_quiz_questions_options_gin ON public.training_quiz_questions USING gin(options);
\nCREATE INDEX IF NOT EXISTS idx_transactions_metadata_gin ON public.transactions USING gin(metadata);
\n\n-- JSONB GIN Indexes - Travel\nCREATE INDEX IF NOT EXISTS idx_travel_bookings_traveler_info_gin ON public.travel_bookings USING gin(traveler_info);
\nCREATE INDEX IF NOT EXISTS idx_travel_offers_offer_data_gin ON public.travel_offers USING gin(offer_data);
\nCREATE INDEX IF NOT EXISTS idx_travel_order_items_meta_gin ON public.travel_order_items USING gin(meta);
\nCREATE INDEX IF NOT EXISTS idx_travel_order_items_supplier_payload_gin ON public.travel_order_items USING gin(supplier_payload);
\nCREATE INDEX IF NOT EXISTS idx_travel_partners_tracking_params_gin ON public.travel_partners USING gin(tracking_params);
\nCREATE INDEX IF NOT EXISTS idx_travel_search_sessions_search_params_gin ON public.travel_search_sessions USING gin(search_params);
\nCREATE INDEX IF NOT EXISTS idx_trip_items_metadata_gin ON public.trip_items USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_trips_dropoff_location_gin ON public.trips USING gin(dropoff_location);
\nCREATE INDEX IF NOT EXISTS idx_trips_pickup_location_gin ON public.trips USING gin(pickup_location);
\nCREATE INDEX IF NOT EXISTS idx_trips_rating_categories_gin ON public.trips USING gin(rating_categories);
\n\n-- JSONB GIN Indexes - User\nCREATE INDEX IF NOT EXISTS idx_user_behavior_signals_metadata_gin ON public.user_behavior_signals USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_user_clv_scores_factors_gin ON public.user_clv_scores USING gin(factors);
\nCREATE INDEX IF NOT EXISTS idx_user_devices_device_info_gin ON public.user_devices USING gin(device_info);
\nCREATE INDEX IF NOT EXISTS idx_user_favorites_item_data_gin ON public.user_favorites USING gin(item_data);
\nCREATE INDEX IF NOT EXISTS idx_user_preferences_preferences_gin ON public.user_preferences USING gin(preferences);
\nCREATE INDEX IF NOT EXISTS idx_user_recently_viewed_item_data_gin ON public.user_recently_viewed USING gin(item_data);
\nCREATE INDEX IF NOT EXISTS idx_user_saved_searches_search_params_gin ON public.user_saved_searches USING gin(search_params);
\n\n-- JSONB GIN Indexes - Vehicle and Wallet\nCREATE INDEX IF NOT EXISTS idx_vehicle_delivery_tasks_vehicle_photos_gin ON public.vehicle_delivery_tasks USING gin(vehicle_photos);
\nCREATE INDEX IF NOT EXISTS idx_wallet_transactions_metadata_gin ON public.wallet_transactions USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_webhook_event_logs_metadata_gin ON public.webhook_event_logs USING gin(metadata);
\n\n-- JSONB GIN Indexes - Zivo\nCREATE INDEX IF NOT EXISTS idx_zivo_cross_sell_suggestions_context_gin ON public.zivo_cross_sell_suggestions USING gin(context);
\nCREATE INDEX IF NOT EXISTS idx_zivo_growth_config_config_value_gin ON public.zivo_growth_config USING gin(config_value);
\nCREATE INDEX IF NOT EXISTS idx_zivo_payouts_metadata_gin ON public.zivo_payouts USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_zivo_revenue_metadata_gin ON public.zivo_revenue USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_zivo_subscription_plans_benefits_gin ON public.zivo_subscription_plans USING gin(benefits);
\nCREATE INDEX IF NOT EXISTS idx_zivo_support_messages_attachments_gin ON public.zivo_support_messages USING gin(attachments);
\nCREATE INDEX IF NOT EXISTS idx_zivo_support_tickets_metadata_gin ON public.zivo_support_tickets USING gin(metadata);
\nCREATE INDEX IF NOT EXISTS idx_zivo_wallet_transactions_metadata_gin ON public.zivo_wallet_transactions USING gin(metadata);
\n\n-- Array GIN Indexes\nCREATE INDEX IF NOT EXISTS idx_api_partners_permissions_gin ON public.api_partners USING gin(permissions);
\nCREATE INDEX IF NOT EXISTS idx_auto_incentive_rules_target_zone_codes_gin ON public.auto_incentive_rules USING gin(target_zone_codes);
\nCREATE INDEX IF NOT EXISTS idx_automation_reply_templates_trigger_keywords_gin ON public.automation_reply_templates USING gin(trigger_keywords);
\nCREATE INDEX IF NOT EXISTS idx_brands_services_available_gin ON public.brands USING gin(services_available);
\nCREATE INDEX IF NOT EXISTS idx_business_account_users_approved_services_gin ON public.business_account_users USING gin(approved_services);
\nCREATE INDEX IF NOT EXISTS idx_business_policies_allowed_cities_gin ON public.business_policies USING gin(allowed_cities);
\nCREATE INDEX IF NOT EXISTS idx_business_policies_restricted_zones_gin ON public.business_policies USING gin(restricted_zones);
\nCREATE INDEX IF NOT EXISTS idx_city_launches_services_enabled_gin ON public.city_launches USING gin(services_enabled);
\nCREATE INDEX IF NOT EXISTS idx_compliance_policies_reminder_days_gin ON public.compliance_policies USING gin(reminder_days);
\nCREATE INDEX IF NOT EXISTS idx_compliance_requirements_cache_expired_documents_gin ON public.compliance_requirements_cache USING gin(expired_documents);
\nCREATE INDEX IF NOT EXISTS idx_compliance_requirements_cache_missing_documents_gin ON public.compliance_requirements_cache USING gin(missing_documents);
\nCREATE INDEX IF NOT EXISTS idx_compliance_requirements_cache_pending_documents_gin ON public.compliance_requirements_cache USING gin(pending_documents);
\nCREATE INDEX IF NOT EXISTS idx_compliance_requirements_cache_rejected_documents_gin ON public.compliance_requirements_cache USING gin(rejected_documents);
\nCREATE INDEX IF NOT EXISTS idx_compliance_requirements_cache_required_documents_gin ON public.compliance_requirements_cache USING gin(required_documents);
\nCREATE INDEX IF NOT EXISTS idx_country_tax_config_applies_to_gin ON public.country_tax_config USING gin(applies_to);
\nCREATE INDEX IF NOT EXISTS idx_dr_active_incidents_affected_services_gin ON public.dr_active_incidents USING gin(affected_services);
\nCREATE INDEX IF NOT EXISTS idx_drivers_allowed_regions_gin ON public.drivers USING gin(allowed_regions);
\nCREATE INDEX IF NOT EXISTS idx_eats_reviews_tags_gin ON public.eats_reviews USING gin(tags);
\nCREATE INDEX IF NOT EXISTS idx_experiments_metric_secondary_gin ON public.experiments USING gin(metric_secondary);
\nCREATE INDEX IF NOT EXISTS idx_food_orders_risk_signals_gin ON public.food_orders USING gin(risk_signals);
\nCREATE INDEX IF NOT EXISTS idx_fraud_assessments_reasons_gin ON public.fraud_assessments USING gin(reasons);
\nCREATE INDEX IF NOT EXISTS idx_happy_hours_days_of_week_gin ON public.happy_hours USING gin(days_of_week);
\nCREATE INDEX IF NOT EXISTS idx_incident_templates_variables_gin ON public.incident_templates USING gin(variables);
\nCREATE INDEX IF NOT EXISTS idx_knowledge_base_articles_tags_gin ON public.knowledge_base_articles USING gin(tags);
\nCREATE INDEX IF NOT EXISTS idx_kyc_submissions_completed_steps_gin ON public.kyc_submissions USING gin(completed_steps);
\nCREATE INDEX IF NOT EXISTS idx_launch_cities_services_available_gin ON public.launch_cities USING gin(services_available);
\nCREATE INDEX IF NOT EXISTS idx_launch_settings_announcement_cities_gin ON public.launch_settings USING gin(announcement_cities);
\nCREATE INDEX IF NOT EXISTS idx_legal_policies_applies_to_gin ON public.legal_policies USING gin(applies_to);
\nCREATE INDEX IF NOT EXISTS idx_maintenance_history_affected_services_gin ON public.maintenance_history USING gin(affected_services);
\nCREATE INDEX IF NOT EXISTS idx_maintenance_mode_affected_services_gin ON public.maintenance_mode USING gin(affected_services);
\nCREATE INDEX IF NOT EXISTS idx_order_ratings_tags_gin ON public.order_ratings USING gin(tags);
\nCREATE INDEX IF NOT EXISTS idx_p2p_payouts_booking_ids_gin ON public.p2p_payouts USING gin(booking_ids);
\nCREATE INDEX IF NOT EXISTS idx_passenger_ratings_tags_gin ON public.passenger_ratings USING gin(tags);
\nCREATE INDEX IF NOT EXISTS idx_peak_events_zones_gin ON public.peak_events USING gin(zones);
\nCREATE INDEX IF NOT EXISTS idx_price_calculations_pricing_rules_applied_gin ON public.price_calculations USING gin(pricing_rules_applied);
\nCREATE INDEX IF NOT EXISTS idx_promotions_applicable_services_gin ON public.promotions USING gin(applicable_services);
\nCREATE INDEX IF NOT EXISTS idx_recovery_tests_issues_found_gin ON public.recovery_tests USING gin(issues_found);
\nCREATE INDEX IF NOT EXISTS idx_regions_services_enabled_gin ON public.regions USING gin(services_enabled);
\nCREATE INDEX IF NOT EXISTS idx_restaurant_reviews_tags_gin ON public.restaurant_reviews USING gin(tags);
\nCREATE INDEX IF NOT EXISTS idx_restore_operations_affected_tables_gin ON public.restore_operations USING gin(affected_tables);
\nCREATE INDEX IF NOT EXISTS idx_role_terms_liabilities_gin ON public.role_terms USING gin(liabilities);
\nCREATE INDEX IF NOT EXISTS idx_role_terms_responsibilities_gin ON public.role_terms USING gin(responsibilities);
\nCREATE INDEX IF NOT EXISTS idx_scheduled_reports_recipients_gin ON public.scheduled_reports USING gin(recipients);
\nCREATE INDEX IF NOT EXISTS idx_special_fees_service_types_gin ON public.special_fees USING gin(service_types);
\nCREATE INDEX IF NOT EXISTS idx_square_connections_location_ids_gin ON public.square_connections USING gin(location_ids);
\nCREATE INDEX IF NOT EXISTS idx_square_connections_scopes_gin ON public.square_connections USING gin(scopes);
\nCREATE INDEX IF NOT EXISTS idx_square_items_category_ids_gin ON public.square_items USING gin(category_ids);
\nCREATE INDEX IF NOT EXISTS idx_support_tickets_tags_gin ON public.support_tickets USING gin(tags);
\nCREATE INDEX IF NOT EXISTS idx_surge_rules_day_of_week_gin ON public.surge_rules USING gin(day_of_week);
\nCREATE INDEX IF NOT EXISTS idx_system_incidents_affected_zones_gin ON public.system_incidents USING gin(affected_zones);
\nCREATE INDEX IF NOT EXISTS idx_time_based_pricing_rules_days_of_week_gin ON public.time_based_pricing_rules USING gin(days_of_week);
\nCREATE INDEX IF NOT EXISTS idx_traveler_profiles_dietary_preferences_gin ON public.traveler_profiles USING gin(dietary_preferences);
\nCREATE INDEX IF NOT EXISTS idx_trips_rating_tags_gin ON public.trips USING gin(rating_tags);
\nCREATE INDEX IF NOT EXISTS idx_zivo_credits_usable_on_gin ON public.zivo_credits USING gin(usable_on);
\nCREATE INDEX IF NOT EXISTS idx_zivo_promo_campaigns_services_gin ON public.zivo_promo_campaigns USING gin(services);
\nCREATE INDEX IF NOT EXISTS idx_zivo_user_preferences_dietary_restrictions_gin ON public.zivo_user_preferences USING gin(dietary_restrictions);
;
