/*\n  # Add Indexes for Expiration and Completion Timestamps\n\n  1. Performance Improvements\n    - **Expiration Indexes** (30+ columns)\n      - Fast filtering of expired/valid records\n      - Optimizes cleanup jobs and validity checks\n      - Enables efficient date range queries\n    \n    - **Completion Indexes** (20+ columns)\n      - Fast queries for completed/pending tasks\n      - Optimizes status tracking and reporting\n      - Enables efficient date range queries\n\n  2. Index Strategy\n    - Using B-tree indexes for timestamp comparisons\n    - Partial indexes for non-null values\n    - DESC ordering for recent-first queries\n    - Supports range queries and sorting operations\n\n  3. Important Notes\n    - Critical for cleanup jobs and background tasks\n    - Prevents full table scans on expiration checks\n    - Improves query performance for time-based filtering\n    - Essential for session management and token validation\n*/\n\n-- Expiration Indexes\nCREATE INDEX IF NOT EXISTS idx_ai_partner_insights_expires_at ON public.ai_partner_insights(expires_at) WHERE expires_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_ai_pricing_suggestions_expires_at ON public.ai_pricing_suggestions(expires_at) WHERE expires_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_ai_recommendations_expires_at ON public.ai_recommendations(expires_at) WHERE expires_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_announcements_starts_at ON public.announcements(starts_at);
\nCREATE INDEX IF NOT EXISTS idx_announcements_ends_at ON public.announcements(ends_at);
\nCREATE INDEX IF NOT EXISTS idx_announcements_date_range ON public.announcements(starts_at, ends_at);
\nCREATE INDEX IF NOT EXISTS idx_bonus_zones_starts_at ON public.bonus_zones(starts_at);
\nCREATE INDEX IF NOT EXISTS idx_bonus_zones_ends_at ON public.bonus_zones(ends_at);
\nCREATE INDEX IF NOT EXISTS idx_bonus_zones_date_range ON public.bonus_zones(starts_at, ends_at);
\nCREATE INDEX IF NOT EXISTS idx_call_sessions_expires_at ON public.call_sessions(expires_at);
\nCREATE INDEX IF NOT EXISTS idx_car_owner_documents_expires_at ON public.car_owner_documents(expires_at) WHERE expires_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_city_health_recommendations_expires_at ON public.city_health_recommendations(expires_at) WHERE expires_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_company_invite_codes_expires_at ON public.company_invite_codes(expires_at);
\nCREATE INDEX IF NOT EXISTS idx_coupons_expires_at ON public.coupons(expires_at);
\nCREATE INDEX IF NOT EXISTS idx_driver_document_status_expires_at ON public.driver_document_status(expires_at) WHERE expires_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_gift_cards_expires_at ON public.gift_cards(expires_at);
\nCREATE INDEX IF NOT EXISTS idx_job_otps_expires_at ON public.job_otps(expires_at);
\nCREATE INDEX IF NOT EXISTS idx_legal_policies_expires_at ON public.legal_policies(expires_at) WHERE expires_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_login_sessions_expires_at ON public.login_sessions(expires_at);
\nCREATE INDEX IF NOT EXISTS idx_merchant_coupons_starts_at ON public.merchant_coupons(starts_at);
\nCREATE INDEX IF NOT EXISTS idx_merchant_coupons_ends_at ON public.merchant_coupons(ends_at);
\nCREATE INDEX IF NOT EXISTS idx_merchant_coupons_date_range ON public.merchant_coupons(starts_at, ends_at);
\nCREATE INDEX IF NOT EXISTS idx_order_offers_expires_at ON public.order_offers(expires_at);
\nCREATE INDEX IF NOT EXISTS idx_p2p_renter_invites_expires_at ON public.p2p_renter_invites(expires_at);
\nCREATE INDEX IF NOT EXISTS idx_personalized_offers_expires_at ON public.personalized_offers(expires_at);
\nCREATE INDEX IF NOT EXISTS idx_platform_rewards_valid_from ON public.platform_rewards(valid_from);
\nCREATE INDEX IF NOT EXISTS idx_platform_rewards_valid_until ON public.platform_rewards(valid_until);
\nCREATE INDEX IF NOT EXISTS idx_platform_rewards_date_range ON public.platform_rewards(valid_from, valid_until);
\nCREATE INDEX IF NOT EXISTS idx_promo_codes_expires_at ON public.promo_codes(expires_at);
\nCREATE INDEX IF NOT EXISTS idx_referral_campaigns_starts_at ON public.referral_campaigns(starts_at);
\nCREATE INDEX IF NOT EXISTS idx_referral_campaigns_expires_at ON public.referral_campaigns(expires_at);
\nCREATE INDEX IF NOT EXISTS idx_referral_campaigns_date_range ON public.referral_campaigns(starts_at, expires_at);
\nCREATE INDEX IF NOT EXISTS idx_reward_redemptions_expires_at ON public.reward_redemptions(expires_at);
\nCREATE INDEX IF NOT EXISTS idx_reward_rules_valid_from ON public.reward_rules(valid_from);
\nCREATE INDEX IF NOT EXISTS idx_reward_rules_valid_until ON public.reward_rules(valid_until);
\nCREATE INDEX IF NOT EXISTS idx_reward_rules_date_range ON public.reward_rules(valid_from, valid_until);
\nCREATE INDEX IF NOT EXISTS idx_rewards_expires_at ON public.rewards(expires_at);
\nCREATE INDEX IF NOT EXISTS idx_ride_offers_expires_at ON public.ride_offers(expires_at);
\n\n-- Completion Indexes\nCREATE INDEX IF NOT EXISTS idx_batch_stops_completed_at ON public.batch_stops(completed_at DESC) WHERE completed_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_city_launch_checklist_completed_at ON public.city_launch_checklist(completed_at DESC) WHERE completed_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_compliance_reviews_completed_at ON public.compliance_reviews(completed_at DESC) WHERE completed_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_delivery_batches_completed_at ON public.delivery_batches(completed_at DESC) WHERE completed_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_driver_daily_goals_completed_at ON public.driver_daily_goals(completed_at DESC) WHERE completed_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_driver_earnings_goals_completed_at ON public.driver_earnings_goals(completed_at DESC) WHERE completed_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_driver_referrals_completed_at ON public.driver_referrals(completed_at DESC) WHERE completed_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_driver_training_progress_completed_at ON public.driver_training_progress(completed_at DESC) WHERE completed_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_jobs_completed_at ON public.jobs(completed_at DESC) WHERE completed_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_launch_phase_log_completed_at ON public.launch_phase_log(completed_at DESC) WHERE completed_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_lost_item_requests_completed_at ON public.lost_item_requests(completed_at DESC) WHERE completed_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_menu_import_logs_completed_at ON public.menu_import_logs(completed_at DESC) WHERE completed_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_merchant_payout_runs_completed_at ON public.merchant_payout_runs(completed_at DESC) WHERE completed_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_operations_checklists_completed_at ON public.operations_checklists(completed_at DESC) WHERE completed_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_payout_runs_completed_at ON public.payout_runs(completed_at DESC) WHERE completed_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_recovery_tests_scheduled_at ON public.recovery_tests(scheduled_at);
\nCREATE INDEX IF NOT EXISTS idx_recovery_tests_completed_at ON public.recovery_tests(completed_at DESC) WHERE completed_at IS NOT NULL;
\nCREATE INDEX IF NOT EXISTS idx_restore_operations_completed_at ON public.restore_operations(completed_at DESC) WHERE completed_at IS NOT NULL;
;
