
-- STEP 1: Insert regions (text[] for services_enabled)
INSERT INTO regions (name, city, state, country, currency, timezone, center_lat, center_lng, services_enabled, is_active) VALUES
('Birmingham Metro', 'Birmingham', 'AL', 'US', 'USD', 'America/Chicago', 33.5207, -86.8025, '{ride,eats,delivery}', true),
('Montgomery Metro', 'Montgomery', 'AL', 'US', 'USD', 'America/Chicago', 32.3792, -86.3077, '{ride,eats,delivery}', true),
('Huntsville Metro', 'Huntsville', 'AL', 'US', 'USD', 'America/Chicago', 34.7304, -86.5861, '{ride,eats,delivery}', true),
('Anchorage Metro', 'Anchorage', 'AK', 'US', 'USD', 'America/Anchorage', 61.2181, -149.9003, '{ride,eats,delivery}', true),
('Fairbanks Metro', 'Fairbanks', 'AK', 'US', 'USD', 'America/Anchorage', 64.8378, -147.7164, '{ride,eats,delivery}', true),
('Phoenix Metro', 'Phoenix', 'AZ', 'US', 'USD', 'America/Phoenix', 33.4484, -112.0740, '{ride,eats,delivery}', true),
('Tucson Metro', 'Tucson', 'AZ', 'US', 'USD', 'America/Phoenix', 32.2226, -110.9747, '{ride,eats,delivery}', true),
('Mesa Metro', 'Mesa', 'AZ', 'US', 'USD', 'America/Phoenix', 33.4152, -111.8315, '{ride,eats,delivery}', true),
('Little Rock Metro', 'Little Rock', 'AR', 'US', 'USD', 'America/Chicago', 34.7465, -92.2896, '{ride,eats,delivery}', true),
('Fayetteville Metro', 'Fayetteville', 'AR', 'US', 'USD', 'America/Chicago', 36.0626, -94.1574, '{ride,eats,delivery}', true),
('San Francisco Metro', 'San Francisco', 'CA', 'US', 'USD', 'America/Los_Angeles', 37.7749, -122.4194, '{ride,eats,delivery}', true),
('San Diego Metro', 'San Diego', 'CA', 'US', 'USD', 'America/Los_Angeles', 32.7157, -117.1611, '{ride,eats,delivery}', true),
('Sacramento Metro', 'Sacramento', 'CA', 'US', 'USD', 'America/Los_Angeles', 38.5816, -121.4944, '{ride,eats,delivery}', true),
('San Jose Metro', 'San Jose', 'CA', 'US', 'USD', 'America/Los_Angeles', 37.3382, -121.8863, '{ride,eats,delivery}', true),
('Fresno Metro', 'Fresno', 'CA', 'US', 'USD', 'America/Los_Angeles', 36.7378, -119.7871, '{ride,eats,delivery}', true),
('Denver Metro', 'Denver', 'CO', 'US', 'USD', 'America/Denver', 39.7392, -104.9903, '{ride,eats,delivery}', true),
('Colorado Springs Metro', 'Colorado Springs', 'CO', 'US', 'USD', 'America/Denver', 38.8339, -104.8214, '{ride,eats,delivery}', true),
('Aurora Metro', 'Aurora', 'CO', 'US', 'USD', 'America/Denver', 39.7294, -104.8319, '{ride,eats,delivery}', true),
('Hartford Metro', 'Hartford', 'CT', 'US', 'USD', 'America/New_York', 41.7658, -72.6734, '{ride,eats,delivery}', true),
('New Haven Metro', 'New Haven', 'CT', 'US', 'USD', 'America/New_York', 41.3083, -72.9279, '{ride,eats,delivery}', true),
('Bridgeport Metro', 'Bridgeport', 'CT', 'US', 'USD', 'America/New_York', 41.1865, -73.1952, '{ride,eats,delivery}', true),
('Wilmington Metro', 'Wilmington', 'DE', 'US', 'USD', 'America/New_York', 39.7391, -75.5398, '{ride,eats,delivery}', true),
('Dover Metro', 'Dover', 'DE', 'US', 'USD', 'America/New_York', 39.1582, -75.5244, '{ride,eats,delivery}', true),
('Miami Metro', 'Miami', 'FL', 'US', 'USD', 'America/New_York', 25.7617, -80.1918, '{ride,eats,delivery}', true),
('Tampa Metro', 'Tampa', 'FL', 'US', 'USD', 'America/New_York', 27.9506, -82.4572, '{ride,eats,delivery}', true),
('Orlando Metro', 'Orlando', 'FL', 'US', 'USD', 'America/New_York', 28.5383, -81.3792, '{ride,eats,delivery}', true),
('Jacksonville Metro', 'Jacksonville', 'FL', 'US', 'USD', 'America/New_York', 30.3322, -81.6557, '{ride,eats,delivery}', true),
('Fort Lauderdale Metro', 'Fort Lauderdale', 'FL', 'US', 'USD', 'America/New_York', 26.1224, -80.1373, '{ride,eats,delivery}', true),
('Atlanta Metro', 'Atlanta', 'GA', 'US', 'USD', 'America/New_York', 33.7490, -84.3880, '{ride,eats,delivery}', true),
('Savannah Metro', 'Savannah', 'GA', 'US', 'USD', 'America/New_York', 32.0809, -81.0912, '{ride,eats,delivery}', true),
('Augusta Metro', 'Augusta', 'GA', 'US', 'USD', 'America/New_York', 33.4735, -81.9748, '{ride,eats,delivery}', true),
('Honolulu Metro', 'Honolulu', 'HI', 'US', 'USD', 'Pacific/Honolulu', 21.3069, -157.8583, '{ride,eats,delivery}', true),
('Boise Metro', 'Boise', 'ID', 'US', 'USD', 'America/Boise', 43.6150, -116.2023, '{ride,eats,delivery}', true),
('Idaho Falls Metro', 'Idaho Falls', 'ID', 'US', 'USD', 'America/Boise', 43.4917, -112.0339, '{ride,eats,delivery}', true),
('Springfield Metro', 'Springfield', 'IL', 'US', 'USD', 'America/Chicago', 39.7817, -89.6501, '{ride,eats,delivery}', true),
('Peoria Metro', 'Peoria', 'IL', 'US', 'USD', 'America/Chicago', 40.6936, -89.5890, '{ride,eats,delivery}', true),
('Rockford Metro', 'Rockford', 'IL', 'US', 'USD', 'America/Chicago', 42.2711, -89.0940, '{ride,eats,delivery}', true),
('Indianapolis Metro', 'Indianapolis', 'IN', 'US', 'USD', 'America/Indiana/Indianapolis', 39.7684, -86.1581, '{ride,eats,delivery}', true),
('Fort Wayne Metro', 'Fort Wayne', 'IN', 'US', 'USD', 'America/Indiana/Indianapolis', 41.0793, -85.1394, '{ride,eats,delivery}', true),
('Evansville Metro', 'Evansville', 'IN', 'US', 'USD', 'America/Indiana/Indianapolis', 37.9716, -87.5711, '{ride,eats,delivery}', true),
('Des Moines Metro', 'Des Moines', 'IA', 'US', 'USD', 'America/Chicago', 41.5868, -93.6250, '{ride,eats,delivery}', true),
('Cedar Rapids Metro', 'Cedar Rapids', 'IA', 'US', 'USD', 'America/Chicago', 41.9779, -91.6656, '{ride,eats,delivery}', true),
('Wichita Metro', 'Wichita', 'KS', 'US', 'USD', 'America/Chicago', 37.6872, -97.3301, '{ride,eats,delivery}', true),
('Kansas City KS Metro', 'Kansas City KS', 'KS', 'US', 'USD', 'America/Chicago', 39.1141, -94.6275, '{ride,eats,delivery}', true),
('Overland Park Metro', 'Overland Park', 'KS', 'US', 'USD', 'America/Chicago', 38.9822, -94.6708, '{ride,eats,delivery}', true),
('Louisville Metro', 'Louisville', 'KY', 'US', 'USD', 'America/Kentucky/Louisville', 38.2527, -85.7585, '{ride,eats,delivery}', true),
('Lexington Metro', 'Lexington', 'KY', 'US', 'USD', 'America/Kentucky/Louisville', 38.0406, -84.5037, '{ride,eats,delivery}', true),
('New Orleans Metro', 'New Orleans', 'LA', 'US', 'USD', 'America/Chicago', 29.9511, -90.0715, '{ride,eats,delivery}', true),
('Baton Rouge Metro', 'Baton Rouge', 'LA', 'US', 'USD', 'America/Chicago', 30.4515, -91.1871, '{ride,eats,delivery}', true),
('Shreveport Metro', 'Shreveport', 'LA', 'US', 'USD', 'America/Chicago', 32.5252, -93.7502, '{ride,eats,delivery}', true),
('Portland ME Metro', 'Portland ME', 'ME', 'US', 'USD', 'America/New_York', 43.6591, -70.2568, '{ride,eats,delivery}', true),
('Bangor Metro', 'Bangor', 'ME', 'US', 'USD', 'America/New_York', 44.8012, -68.7778, '{ride,eats,delivery}', true),
('Baltimore Metro', 'Baltimore', 'MD', 'US', 'USD', 'America/New_York', 39.2904, -76.6122, '{ride,eats,delivery}', true),
('Annapolis Metro', 'Annapolis', 'MD', 'US', 'USD', 'America/New_York', 38.9784, -76.4922, '{ride,eats,delivery}', true),
('Boston Metro', 'Boston', 'MA', 'US', 'USD', 'America/New_York', 42.3601, -71.0589, '{ride,eats,delivery}', true),
('Worcester Metro', 'Worcester', 'MA', 'US', 'USD', 'America/New_York', 42.2626, -71.8023, '{ride,eats,delivery}', true),
('Springfield MA Metro', 'Springfield MA', 'MA', 'US', 'USD', 'America/New_York', 42.1015, -72.5898, '{ride,eats,delivery}', true),
('Detroit Metro', 'Detroit', 'MI', 'US', 'USD', 'America/Detroit', 42.3314, -83.0458, '{ride,eats,delivery}', true),
('Grand Rapids Metro', 'Grand Rapids', 'MI', 'US', 'USD', 'America/Detroit', 42.9634, -85.6681, '{ride,eats,delivery}', true),
('Ann Arbor Metro', 'Ann Arbor', 'MI', 'US', 'USD', 'America/Detroit', 42.2808, -83.7430, '{ride,eats,delivery}', true),
('Minneapolis Metro', 'Minneapolis', 'MN', 'US', 'USD', 'America/Chicago', 44.9778, -93.2650, '{ride,eats,delivery}', true),
('Saint Paul Metro', 'Saint Paul', 'MN', 'US', 'USD', 'America/Chicago', 44.9537, -93.0900, '{ride,eats,delivery}', true),
('Rochester MN Metro', 'Rochester MN', 'MN', 'US', 'USD', 'America/Chicago', 44.0121, -92.4802, '{ride,eats,delivery}', true),
('Jackson Metro', 'Jackson', 'MS', 'US', 'USD', 'America/Chicago', 32.2988, -90.1848, '{ride,eats,delivery}', true),
('Gulfport Metro', 'Gulfport', 'MS', 'US', 'USD', 'America/Chicago', 30.3674, -89.0928, '{ride,eats,delivery}', true),
('Kansas City MO Metro', 'Kansas City MO', 'MO', 'US', 'USD', 'America/Chicago', 39.0997, -94.5786, '{ride,eats,delivery}', true),
('Saint Louis Metro', 'Saint Louis', 'MO', 'US', 'USD', 'America/Chicago', 38.6270, -90.1994, '{ride,eats,delivery}', true),
('Springfield MO Metro', 'Springfield MO', 'MO', 'US', 'USD', 'America/Chicago', 37.2090, -93.2923, '{ride,eats,delivery}', true),
('Billings Metro', 'Billings', 'MT', 'US', 'USD', 'America/Denver', 45.7833, -108.5007, '{ride,eats,delivery}', true),
('Missoula Metro', 'Missoula', 'MT', 'US', 'USD', 'America/Denver', 46.8721, -113.9940, '{ride,eats,delivery}', true),
('Omaha Metro', 'Omaha', 'NE', 'US', 'USD', 'America/Chicago', 41.2565, -95.9345, '{ride,eats,delivery}', true),
('Lincoln Metro', 'Lincoln', 'NE', 'US', 'USD', 'America/Chicago', 40.8136, -96.7026, '{ride,eats,delivery}', true),
('Las Vegas Metro', 'Las Vegas', 'NV', 'US', 'USD', 'America/Los_Angeles', 36.1699, -115.1398, '{ride,eats,delivery}', true),
('Reno Metro', 'Reno', 'NV', 'US', 'USD', 'America/Los_Angeles', 39.5296, -119.8138, '{ride,eats,delivery}', true),
('Manchester NH Metro', 'Manchester NH', 'NH', 'US', 'USD', 'America/New_York', 42.9956, -71.4548, '{ride,eats,delivery}', true),
('Nashua Metro', 'Nashua', 'NH', 'US', 'USD', 'America/New_York', 42.7654, -71.4676, '{ride,eats,delivery}', true),
('Newark Metro', 'Newark', 'NJ', 'US', 'USD', 'America/New_York', 40.7357, -74.1724, '{ride,eats,delivery}', true),
('Jersey City Metro', 'Jersey City', 'NJ', 'US', 'USD', 'America/New_York', 40.7178, -74.0431, '{ride,eats,delivery}', true),
('Trenton Metro', 'Trenton', 'NJ', 'US', 'USD', 'America/New_York', 40.2171, -74.7429, '{ride,eats,delivery}', true),
('Albuquerque Metro', 'Albuquerque', 'NM', 'US', 'USD', 'America/Denver', 35.0844, -106.6504, '{ride,eats,delivery}', true),
('Santa Fe Metro', 'Santa Fe', 'NM', 'US', 'USD', 'America/Denver', 35.6870, -105.9378, '{ride,eats,delivery}', true),
('Buffalo Metro', 'Buffalo', 'NY', 'US', 'USD', 'America/New_York', 42.8864, -78.8784, '{ride,eats,delivery}', true),
('Rochester NY Metro', 'Rochester NY', 'NY', 'US', 'USD', 'America/New_York', 43.1566, -77.6088, '{ride,eats,delivery}', true),
('Albany Metro', 'Albany', 'NY', 'US', 'USD', 'America/New_York', 42.6526, -73.7562, '{ride,eats,delivery}', true),
('Syracuse Metro', 'Syracuse', 'NY', 'US', 'USD', 'America/New_York', 43.0481, -76.1474, '{ride,eats,delivery}', true),
('Charlotte Metro', 'Charlotte', 'NC', 'US', 'USD', 'America/New_York', 35.2271, -80.8431, '{ride,eats,delivery}', true),
('Raleigh Metro', 'Raleigh', 'NC', 'US', 'USD', 'America/New_York', 35.7796, -78.6382, '{ride,eats,delivery}', true),
('Durham Metro', 'Durham', 'NC', 'US', 'USD', 'America/New_York', 35.9940, -78.8986, '{ride,eats,delivery}', true),
('Greensboro Metro', 'Greensboro', 'NC', 'US', 'USD', 'America/New_York', 36.0726, -79.7920, '{ride,eats,delivery}', true),
('Fargo Metro', 'Fargo', 'ND', 'US', 'USD', 'America/Chicago', 46.8772, -96.7898, '{ride,eats,delivery}', true),
('Bismarck Metro', 'Bismarck', 'ND', 'US', 'USD', 'America/Chicago', 46.8083, -100.7837, '{ride,eats,delivery}', true),
('Columbus Metro', 'Columbus', 'OH', 'US', 'USD', 'America/New_York', 39.9612, -82.9988, '{ride,eats,delivery}', true),
('Cleveland Metro', 'Cleveland', 'OH', 'US', 'USD', 'America/New_York', 41.4993, -81.6944, '{ride,eats,delivery}', true),
('Cincinnati Metro', 'Cincinnati', 'OH', 'US', 'USD', 'America/New_York', 39.1031, -84.5120, '{ride,eats,delivery}', true),
('Toledo Metro', 'Toledo', 'OH', 'US', 'USD', 'America/New_York', 41.6528, -83.5379, '{ride,eats,delivery}', true),
('Oklahoma City Metro', 'Oklahoma City', 'OK', 'US', 'USD', 'America/Chicago', 35.4676, -97.5164, '{ride,eats,delivery}', true),
('Tulsa Metro', 'Tulsa', 'OK', 'US', 'USD', 'America/Chicago', 36.1540, -95.9928, '{ride,eats,delivery}', true),
('Portland OR Metro', 'Portland OR', 'OR', 'US', 'USD', 'America/Los_Angeles', 45.5152, -122.6784, '{ride,eats,delivery}', true),
('Salem Metro', 'Salem', 'OR', 'US', 'USD', 'America/Los_Angeles', 44.9429, -123.0351, '{ride,eats,delivery}', true),
('Eugene Metro', 'Eugene', 'OR', 'US', 'USD', 'America/Los_Angeles', 44.0521, -123.0868, '{ride,eats,delivery}', true),
('Philadelphia Metro', 'Philadelphia', 'PA', 'US', 'USD', 'America/New_York', 39.9526, -75.1652, '{ride,eats,delivery}', true),
('Pittsburgh Metro', 'Pittsburgh', 'PA', 'US', 'USD', 'America/New_York', 40.4406, -79.9959, '{ride,eats,delivery}', true),
('Harrisburg Metro', 'Harrisburg', 'PA', 'US', 'USD', 'America/New_York', 40.2732, -76.8867, '{ride,eats,delivery}', true),
('Providence Metro', 'Providence', 'RI', 'US', 'USD', 'America/New_York', 41.8240, -71.4128, '{ride,eats,delivery}', true),
('Charleston SC Metro', 'Charleston SC', 'SC', 'US', 'USD', 'America/New_York', 32.7765, -79.9311, '{ride,eats,delivery}', true),
('Columbia SC Metro', 'Columbia SC', 'SC', 'US', 'USD', 'America/New_York', 34.0007, -81.0348, '{ride,eats,delivery}', true),
('Greenville Metro', 'Greenville', 'SC', 'US', 'USD', 'America/New_York', 34.8526, -82.3940, '{ride,eats,delivery}', true),
('Sioux Falls Metro', 'Sioux Falls', 'SD', 'US', 'USD', 'America/Chicago', 43.5446, -96.7311, '{ride,eats,delivery}', true),
('Rapid City Metro', 'Rapid City', 'SD', 'US', 'USD', 'America/Denver', 44.0805, -103.2310, '{ride,eats,delivery}', true),
('Nashville Metro', 'Nashville', 'TN', 'US', 'USD', 'America/Chicago', 36.1627, -86.7816, '{ride,eats,delivery}', true),
('Memphis Metro', 'Memphis', 'TN', 'US', 'USD', 'America/Chicago', 35.1495, -90.0490, '{ride,eats,delivery}', true),
('Knoxville Metro', 'Knoxville', 'TN', 'US', 'USD', 'America/New_York', 35.9606, -83.9207, '{ride,eats,delivery}', true),
('Chattanooga Metro', 'Chattanooga', 'TN', 'US', 'USD', 'America/New_York', 35.0456, -85.3097, '{ride,eats,delivery}', true),
('Houston Metro', 'Houston', 'TX', 'US', 'USD', 'America/Chicago', 29.7604, -95.3698, '{ride,eats,delivery}', true),
('Dallas Metro', 'Dallas', 'TX', 'US', 'USD', 'America/Chicago', 32.7767, -96.7970, '{ride,eats,delivery}', true),
('Austin Metro', 'Austin', 'TX', 'US', 'USD', 'America/Chicago', 30.2672, -97.7431, '{ride,eats,delivery}', true),
('San Antonio Metro', 'San Antonio', 'TX', 'US', 'USD', 'America/Chicago', 29.4241, -98.4936, '{ride,eats,delivery}', true),
('Fort Worth Metro', 'Fort Worth', 'TX', 'US', 'USD', 'America/Chicago', 32.7555, -97.3308, '{ride,eats,delivery}', true),
('El Paso Metro', 'El Paso', 'TX', 'US', 'USD', 'America/Denver', 31.7619, -106.4850, '{ride,eats,delivery}', true),
('Salt Lake City Metro', 'Salt Lake City', 'UT', 'US', 'USD', 'America/Denver', 40.7608, -111.8910, '{ride,eats,delivery}', true),
('Provo Metro', 'Provo', 'UT', 'US', 'USD', 'America/Denver', 40.2338, -111.6585, '{ride,eats,delivery}', true),
('Burlington Metro', 'Burlington', 'VT', 'US', 'USD', 'America/New_York', 44.4759, -73.2121, '{ride,eats,delivery}', true),
('Virginia Beach Metro', 'Virginia Beach', 'VA', 'US', 'USD', 'America/New_York', 36.8529, -75.9780, '{ride,eats,delivery}', true),
('Richmond Metro', 'Richmond', 'VA', 'US', 'USD', 'America/New_York', 37.5407, -77.4360, '{ride,eats,delivery}', true),
('Norfolk Metro', 'Norfolk', 'VA', 'US', 'USD', 'America/New_York', 36.8508, -76.2859, '{ride,eats,delivery}', true),
('Arlington VA Metro', 'Arlington VA', 'VA', 'US', 'USD', 'America/New_York', 38.8799, -77.1068, '{ride,eats,delivery}', true),
('Seattle Metro', 'Seattle', 'WA', 'US', 'USD', 'America/Los_Angeles', 47.6062, -122.3321, '{ride,eats,delivery}', true),
('Spokane Metro', 'Spokane', 'WA', 'US', 'USD', 'America/Los_Angeles', 47.6588, -117.4260, '{ride,eats,delivery}', true),
('Tacoma Metro', 'Tacoma', 'WA', 'US', 'USD', 'America/Los_Angeles', 47.2529, -122.4443, '{ride,eats,delivery}', true),
('Washington DC Metro', 'Washington DC', 'DC', 'US', 'USD', 'America/New_York', 38.9072, -77.0369, '{ride,eats,delivery}', true),
('Charleston WV Metro', 'Charleston WV', 'WV', 'US', 'USD', 'America/New_York', 38.3498, -81.6326, '{ride,eats,delivery}', true),
('Huntington Metro', 'Huntington', 'WV', 'US', 'USD', 'America/New_York', 38.4192, -82.4452, '{ride,eats,delivery}', true),
('Milwaukee Metro', 'Milwaukee', 'WI', 'US', 'USD', 'America/Chicago', 43.0389, -87.9065, '{ride,eats,delivery}', true),
('Madison Metro', 'Madison', 'WI', 'US', 'USD', 'America/Chicago', 43.0731, -89.4012, '{ride,eats,delivery}', true),
('Green Bay Metro', 'Green Bay', 'WI', 'US', 'USD', 'America/Chicago', 44.5133, -88.0133, '{ride,eats,delivery}', true),
('Cheyenne Metro', 'Cheyenne', 'WY', 'US', 'USD', 'America/Denver', 41.1400, -104.8202, '{ride,eats,delivery}', true),
('Casper Metro', 'Casper', 'WY', 'US', 'USD', 'America/Denver', 42.8666, -106.3131, '{ride,eats,delivery}', true);

-- STEP 2: Update existing cities with state/timezone
UPDATE cities SET state = 'FL', timezone = 'America/New_York' WHERE name = 'Miami';
UPDATE cities SET state = 'CA', timezone = 'America/Los_Angeles' WHERE name = 'San Francisco';
UPDATE cities SET state = 'IL', timezone = 'America/Chicago' WHERE name = 'Chicago';
UPDATE cities SET state = 'NY', timezone = 'America/New_York' WHERE name = 'New York';
UPDATE cities SET state = 'CA', timezone = 'America/Los_Angeles' WHERE name = 'Los Angeles';

-- STEP 3: Insert new cities
INSERT INTO cities (name, state, country, currency, timezone, is_active) VALUES
('Birmingham', 'AL', 'US', 'USD', 'America/Chicago', true),
('Montgomery', 'AL', 'US', 'USD', 'America/Chicago', true),
('Huntsville', 'AL', 'US', 'USD', 'America/Chicago', true),
('Anchorage', 'AK', 'US', 'USD', 'America/Anchorage', true),
('Fairbanks', 'AK', 'US', 'USD', 'America/Anchorage', true),
('Phoenix', 'AZ', 'US', 'USD', 'America/Phoenix', true),
('Tucson', 'AZ', 'US', 'USD', 'America/Phoenix', true),
('Mesa', 'AZ', 'US', 'USD', 'America/Phoenix', true),
('Little Rock', 'AR', 'US', 'USD', 'America/Chicago', true),
('Fayetteville', 'AR', 'US', 'USD', 'America/Chicago', true),
('San Diego', 'CA', 'US', 'USD', 'America/Los_Angeles', true),
('Sacramento', 'CA', 'US', 'USD', 'America/Los_Angeles', true),
('San Jose', 'CA', 'US', 'USD', 'America/Los_Angeles', true),
('Fresno', 'CA', 'US', 'USD', 'America/Los_Angeles', true),
('Denver', 'CO', 'US', 'USD', 'America/Denver', true),
('Colorado Springs', 'CO', 'US', 'USD', 'America/Denver', true),
('Aurora', 'CO', 'US', 'USD', 'America/Denver', true),
('Hartford', 'CT', 'US', 'USD', 'America/New_York', true),
('New Haven', 'CT', 'US', 'USD', 'America/New_York', true),
('Bridgeport', 'CT', 'US', 'USD', 'America/New_York', true),
('Wilmington', 'DE', 'US', 'USD', 'America/New_York', true),
('Dover', 'DE', 'US', 'USD', 'America/New_York', true),
('Tampa', 'FL', 'US', 'USD', 'America/New_York', true),
('Orlando', 'FL', 'US', 'USD', 'America/New_York', true),
('Jacksonville', 'FL', 'US', 'USD', 'America/New_York', true),
('Fort Lauderdale', 'FL', 'US', 'USD', 'America/New_York', true),
('Atlanta', 'GA', 'US', 'USD', 'America/New_York', true),
('Savannah', 'GA', 'US', 'USD', 'America/New_York', true),
('Augusta', 'GA', 'US', 'USD', 'America/New_York', true),
('Honolulu', 'HI', 'US', 'USD', 'Pacific/Honolulu', true),
('Boise', 'ID', 'US', 'USD', 'America/Boise', true),
('Idaho Falls', 'ID', 'US', 'USD', 'America/Boise', true),
('Springfield', 'IL', 'US', 'USD', 'America/Chicago', true),
('Peoria', 'IL', 'US', 'USD', 'America/Chicago', true),
('Rockford', 'IL', 'US', 'USD', 'America/Chicago', true),
('Indianapolis', 'IN', 'US', 'USD', 'America/Indiana/Indianapolis', true),
('Fort Wayne', 'IN', 'US', 'USD', 'America/Indiana/Indianapolis', true),
('Evansville', 'IN', 'US', 'USD', 'America/Indiana/Indianapolis', true),
('Des Moines', 'IA', 'US', 'USD', 'America/Chicago', true),
('Cedar Rapids', 'IA', 'US', 'USD', 'America/Chicago', true),
('Wichita', 'KS', 'US', 'USD', 'America/Chicago', true),
('Kansas City KS', 'KS', 'US', 'USD', 'America/Chicago', true),
('Overland Park', 'KS', 'US', 'USD', 'America/Chicago', true),
('Louisville', 'KY', 'US', 'USD', 'America/Kentucky/Louisville', true),
('Lexington', 'KY', 'US', 'USD', 'America/Kentucky/Louisville', true),
('New Orleans', 'LA', 'US', 'USD', 'America/Chicago', true),
('Baton Rouge', 'LA', 'US', 'USD', 'America/Chicago', true),
('Shreveport', 'LA', 'US', 'USD', 'America/Chicago', true),
('Portland ME', 'ME', 'US', 'USD', 'America/New_York', true),
('Bangor', 'ME', 'US', 'USD', 'America/New_York', true),
('Baltimore', 'MD', 'US', 'USD', 'America/New_York', true),
('Annapolis', 'MD', 'US', 'USD', 'America/New_York', true),
('Boston', 'MA', 'US', 'USD', 'America/New_York', true),
('Worcester', 'MA', 'US', 'USD', 'America/New_York', true),
('Springfield MA', 'MA', 'US', 'USD', 'America/New_York', true),
('Detroit', 'MI', 'US', 'USD', 'America/Detroit', true),
('Grand Rapids', 'MI', 'US', 'USD', 'America/Detroit', true),
('Ann Arbor', 'MI', 'US', 'USD', 'America/Detroit', true),
('Minneapolis', 'MN', 'US', 'USD', 'America/Chicago', true),
('Saint Paul', 'MN', 'US', 'USD', 'America/Chicago', true),
('Rochester MN', 'MN', 'US', 'USD', 'America/Chicago', true),
('Jackson', 'MS', 'US', 'USD', 'America/Chicago', true),
('Gulfport', 'MS', 'US', 'USD', 'America/Chicago', true),
('Kansas City MO', 'MO', 'US', 'USD', 'America/Chicago', true),
('Saint Louis', 'MO', 'US', 'USD', 'America/Chicago', true),
('Springfield MO', 'MO', 'US', 'USD', 'America/Chicago', true),
('Billings', 'MT', 'US', 'USD', 'America/Denver', true),
('Missoula', 'MT', 'US', 'USD', 'America/Denver', true),
('Omaha', 'NE', 'US', 'USD', 'America/Chicago', true),
('Lincoln', 'NE', 'US', 'USD', 'America/Chicago', true),
('Las Vegas', 'NV', 'US', 'USD', 'America/Los_Angeles', true),
('Reno', 'NV', 'US', 'USD', 'America/Los_Angeles', true),
('Manchester NH', 'NH', 'US', 'USD', 'America/New_York', true),
('Nashua', 'NH', 'US', 'USD', 'America/New_York', true),
('Newark', 'NJ', 'US', 'USD', 'America/New_York', true),
('Jersey City', 'NJ', 'US', 'USD', 'America/New_York', true),
('Trenton', 'NJ', 'US', 'USD', 'America/New_York', true),
('Albuquerque', 'NM', 'US', 'USD', 'America/Denver', true),
('Santa Fe', 'NM', 'US', 'USD', 'America/Denver', true),
('Buffalo', 'NY', 'US', 'USD', 'America/New_York', true),
('Rochester NY', 'NY', 'US', 'USD', 'America/New_York', true),
('Albany', 'NY', 'US', 'USD', 'America/New_York', true),
('Syracuse', 'NY', 'US', 'USD', 'America/New_York', true),
('Charlotte', 'NC', 'US', 'USD', 'America/New_York', true),
('Raleigh', 'NC', 'US', 'USD', 'America/New_York', true),
('Durham', 'NC', 'US', 'USD', 'America/New_York', true),
('Greensboro', 'NC', 'US', 'USD', 'America/New_York', true),
('Fargo', 'ND', 'US', 'USD', 'America/Chicago', true),
('Bismarck', 'ND', 'US', 'USD', 'America/Chicago', true),
('Columbus', 'OH', 'US', 'USD', 'America/New_York', true),
('Cleveland', 'OH', 'US', 'USD', 'America/New_York', true),
('Cincinnati', 'OH', 'US', 'USD', 'America/New_York', true),
('Toledo', 'OH', 'US', 'USD', 'America/New_York', true),
('Oklahoma City', 'OK', 'US', 'USD', 'America/Chicago', true),
('Tulsa', 'OK', 'US', 'USD', 'America/Chicago', true),
('Portland OR', 'OR', 'US', 'USD', 'America/Los_Angeles', true),
('Salem', 'OR', 'US', 'USD', 'America/Los_Angeles', true),
('Eugene', 'OR', 'US', 'USD', 'America/Los_Angeles', true),
('Philadelphia', 'PA', 'US', 'USD', 'America/New_York', true),
('Pittsburgh', 'PA', 'US', 'USD', 'America/New_York', true),
('Harrisburg', 'PA', 'US', 'USD', 'America/New_York', true),
('Providence', 'RI', 'US', 'USD', 'America/New_York', true),
('Charleston SC', 'SC', 'US', 'USD', 'America/New_York', true),
('Columbia SC', 'SC', 'US', 'USD', 'America/New_York', true),
('Greenville', 'SC', 'US', 'USD', 'America/New_York', true),
('Sioux Falls', 'SD', 'US', 'USD', 'America/Chicago', true),
('Rapid City', 'SD', 'US', 'USD', 'America/Denver', true),
('Nashville', 'TN', 'US', 'USD', 'America/Chicago', true),
('Memphis', 'TN', 'US', 'USD', 'America/Chicago', true),
('Knoxville', 'TN', 'US', 'USD', 'America/New_York', true),
('Chattanooga', 'TN', 'US', 'USD', 'America/New_York', true),
('Houston', 'TX', 'US', 'USD', 'America/Chicago', true),
('Dallas', 'TX', 'US', 'USD', 'America/Chicago', true),
('Austin', 'TX', 'US', 'USD', 'America/Chicago', true),
('San Antonio', 'TX', 'US', 'USD', 'America/Chicago', true),
('Fort Worth', 'TX', 'US', 'USD', 'America/Chicago', true),
('El Paso', 'TX', 'US', 'USD', 'America/Denver', true),
('Salt Lake City', 'UT', 'US', 'USD', 'America/Denver', true),
('Provo', 'UT', 'US', 'USD', 'America/Denver', true),
('Burlington', 'VT', 'US', 'USD', 'America/New_York', true),
('Virginia Beach', 'VA', 'US', 'USD', 'America/New_York', true),
('Richmond', 'VA', 'US', 'USD', 'America/New_York', true),
('Norfolk', 'VA', 'US', 'USD', 'America/New_York', true),
('Arlington VA', 'VA', 'US', 'USD', 'America/New_York', true),
('Seattle', 'WA', 'US', 'USD', 'America/Los_Angeles', true),
('Spokane', 'WA', 'US', 'USD', 'America/Los_Angeles', true),
('Tacoma', 'WA', 'US', 'USD', 'America/Los_Angeles', true),
('Washington DC', 'DC', 'US', 'USD', 'America/New_York', true),
('Charleston WV', 'WV', 'US', 'USD', 'America/New_York', true),
('Huntington', 'WV', 'US', 'USD', 'America/New_York', true),
('Milwaukee', 'WI', 'US', 'USD', 'America/Chicago', true),
('Madison', 'WI', 'US', 'USD', 'America/Chicago', true),
('Green Bay', 'WI', 'US', 'USD', 'America/Chicago', true),
('Cheyenne', 'WY', 'US', 'USD', 'America/Denver', true),
('Casper', 'WY', 'US', 'USD', 'America/Denver', true);

-- STEP 4: Insert eats_zones (services_enabled is JSONB)
INSERT INTO eats_zones (zone_code, city_name, city_id, tax_rate, delivery_fee_base, delivery_fee_per_mile, service_fee_percent, small_order_fee, small_order_threshold, is_active, services_enabled)
SELECT v.zone_code, v.city_name, c.id, v.tax_rate, 2.99, 0.50, 15.00, 2.00, 15.00, true, '["ride","eats","delivery"]'::jsonb
FROM (VALUES
  ('BHM', 'Birmingham', 0.10),
  ('MGM', 'Montgomery', 0.10),
  ('HSV', 'Huntsville', 0.09),
  ('ANC', 'Anchorage', 0.00),
  ('FAI', 'Fairbanks', 0.00),
  ('PHX', 'Phoenix', 0.086),
  ('TUS', 'Tucson', 0.086),
  ('MSA', 'Mesa', 0.078),
  ('LIT', 'Little Rock', 0.095),
  ('FYV', 'Fayetteville', 0.095),
  ('SAN', 'San Diego', 0.0775),
  ('SMF', 'Sacramento', 0.0875),
  ('SJC', 'San Jose', 0.0925),
  ('FAT', 'Fresno', 0.0775),
  ('DEN', 'Denver', 0.0877),
  ('COS', 'Colorado Springs', 0.082),
  ('AUR', 'Aurora', 0.085),
  ('HFD', 'Hartford', 0.0635),
  ('NHV', 'New Haven', 0.0635),
  ('BDR', 'Bridgeport', 0.0635),
  ('WIL', 'Wilmington', 0.00),
  ('DOV', 'Dover', 0.00),
  ('TPA', 'Tampa', 0.075),
  ('MCO', 'Orlando', 0.065),
  ('JAX', 'Jacksonville', 0.075),
  ('FLL', 'Fort Lauderdale', 0.07),
  ('ATL', 'Atlanta', 0.089),
  ('SAV', 'Savannah', 0.07),
  ('AGS', 'Augusta', 0.08),
  ('HNL', 'Honolulu', 0.045),
  ('BOI', 'Boise', 0.06),
  ('IDA', 'Idaho Falls', 0.06),
  ('SPI', 'Springfield', 0.0925),
  ('PIA', 'Peoria', 0.0925),
  ('RFD', 'Rockford', 0.085),
  ('IND', 'Indianapolis', 0.07),
  ('FWA', 'Fort Wayne', 0.07),
  ('EVV', 'Evansville', 0.07),
  ('DSM', 'Des Moines', 0.07),
  ('CID', 'Cedar Rapids', 0.07),
  ('ICT', 'Wichita', 0.0775),
  ('KCK', 'Kansas City KS', 0.095),
  ('OVP', 'Overland Park', 0.0965),
  ('SDF', 'Louisville', 0.06),
  ('LEX', 'Lexington', 0.06),
  ('MSY', 'New Orleans', 0.0945),
  ('BTR', 'Baton Rouge', 0.095),
  ('SHV', 'Shreveport', 0.091),
  ('PWM', 'Portland ME', 0.055),
  ('BGR', 'Bangor', 0.055),
  ('BWI', 'Baltimore', 0.06),
  ('ANP', 'Annapolis', 0.06),
  ('BOS', 'Boston', 0.0625),
  ('ORH', 'Worcester', 0.0625),
  ('SMA', 'Springfield MA', 0.0625),
  ('DTW', 'Detroit', 0.06),
  ('GRR', 'Grand Rapids', 0.06),
  ('ARB', 'Ann Arbor', 0.06),
  ('MSP', 'Minneapolis', 0.0802),
  ('STP', 'Saint Paul', 0.0802),
  ('RST', 'Rochester MN', 0.0762),
  ('JAN', 'Jackson', 0.08),
  ('GPT', 'Gulfport', 0.08),
  ('MCI', 'Kansas City MO', 0.091),
  ('STL', 'Saint Louis', 0.0991),
  ('SGF', 'Springfield MO', 0.0810),
  ('BIL', 'Billings', 0.00),
  ('MSO', 'Missoula', 0.00),
  ('OMA', 'Omaha', 0.07),
  ('LNK', 'Lincoln', 0.0725),
  ('LAS', 'Las Vegas', 0.0838),
  ('RNO', 'Reno', 0.0835),
  ('MHT', 'Manchester NH', 0.00),
  ('ASH', 'Nashua', 0.00),
  ('EWR', 'Newark', 0.06625),
  ('JCY', 'Jersey City', 0.06625),
  ('TTN', 'Trenton', 0.06625),
  ('ABQ', 'Albuquerque', 0.0781),
  ('SAF', 'Santa Fe', 0.0844),
  ('BUF', 'Buffalo', 0.08),
  ('ROC', 'Rochester NY', 0.08),
  ('ALB', 'Albany', 0.08),
  ('SYR', 'Syracuse', 0.08),
  ('CLT', 'Charlotte', 0.0725),
  ('RDU', 'Raleigh', 0.0725),
  ('RDH', 'Durham', 0.075),
  ('GSO', 'Greensboro', 0.0675),
  ('FAR', 'Fargo', 0.075),
  ('BIS', 'Bismarck', 0.075),
  ('CMH', 'Columbus', 0.075),
  ('CLE', 'Cleveland', 0.08),
  ('CVG', 'Cincinnati', 0.075),
  ('TOL', 'Toledo', 0.075),
  ('OKC', 'Oklahoma City', 0.0862),
  ('TUL', 'Tulsa', 0.0867),
  ('PDX', 'Portland OR', 0.00),
  ('SLE', 'Salem', 0.00),
  ('EUG', 'Eugene', 0.00),
  ('PHL', 'Philadelphia', 0.08),
  ('PIT', 'Pittsburgh', 0.07),
  ('MDT', 'Harrisburg', 0.06),
  ('PVD', 'Providence', 0.07),
  ('CHS', 'Charleston SC', 0.09),
  ('CAE', 'Columbia SC', 0.08),
  ('GSP', 'Greenville', 0.07),
  ('FSD', 'Sioux Falls', 0.065),
  ('RAP', 'Rapid City', 0.065),
  ('BNA', 'Nashville', 0.0975),
  ('MEM', 'Memphis', 0.0975),
  ('TYS', 'Knoxville', 0.0975),
  ('CHA', 'Chattanooga', 0.0975),
  ('IAH', 'Houston', 0.0825),
  ('DFW', 'Dallas', 0.0825),
  ('AUS', 'Austin', 0.0825),
  ('SAT', 'San Antonio', 0.0825),
  ('FTW', 'Fort Worth', 0.0825),
  ('ELP', 'El Paso', 0.0825),
  ('SLC', 'Salt Lake City', 0.0710),
  ('PVU', 'Provo', 0.0710),
  ('BTV', 'Burlington', 0.07),
  ('VBH', 'Virginia Beach', 0.06),
  ('RIC', 'Richmond', 0.06),
  ('ORF', 'Norfolk', 0.06),
  ('ARL', 'Arlington VA', 0.06),
  ('SEA', 'Seattle', 0.1025),
  ('GEG', 'Spokane', 0.089),
  ('TCM', 'Tacoma', 0.102),
  ('DCA', 'Washington DC', 0.06),
  ('CRW', 'Charleston WV', 0.07),
  ('HTS', 'Huntington', 0.07),
  ('MKE', 'Milwaukee', 0.056),
  ('MSN', 'Madison', 0.055),
  ('GBY', 'Green Bay', 0.055),
  ('CYS', 'Cheyenne', 0.06),
  ('CPR', 'Casper', 0.06)
) AS v(zone_code, city_name, tax_rate)
JOIN cities c ON c.name = v.city_name
WHERE NOT EXISTS (SELECT 1 FROM eats_zones ez WHERE ez.zone_code = v.zone_code);
;
