/*\n  # Fix Security Issues - Foreign Key Indexes Batch 2\n  \n  This migration continues adding indexes to foreign key columns for improved performance and security.\n  \n  1. **Performance Impact**\n     - Prevents full table scans on foreign key constraint operations\n     - Speeds up JOIN operations across related tables\n     - Improves query optimizer decision making\n     \n  2. **Security Impact**\n     - Faster data integrity checks\n     - Improved response times reduce DoS attack surface\n     - Better performance for audit and compliance queries\n     \n  3. **Tables Affected (Batch 2 - 100 indexes)**\n     - insurance_claims, jobs, launch_compliance_checklist, login_sessions\n     - loyalty_members, loyalty_rewards, loyalty_transactions, maintenance_logs\n     - marketing_campaign_stats, offline_sync_queue, ops_alerts, order_status_history\n     - order_timers, orders, p2p_bookings, p2p_dispute_resolutions\n     - p2p_enhanced_claims, p2p_insurance_claims, p2p_payouts, p2p_protection_commissions\n     - p2p_renter_invites, partner_portal_applications, payout_items, payout_runs\n     - peak_events, performance_adjustments, pricing_assignments, profiles\n     - promo_codes, promotion_usage, purchase_order_items, purchase_orders\n     - push_campaigns, push_notification_logs, rating_flags, recipe_ingredients\n     - recipes, referral_fraud_flags, region_change_logs, reorder_rules\n     - repositioning_alerts, reservations, resolution_evidence, restaurant_branches\n     - restaurant_ledger, restaurants, restore_operations, review_reports\n     - reward_issuances, reward_redemptions, ride_requests, risk_events\n     - risk_scores, scheduled_reports, security_events, service_availability_rules\n     - special_fees, staff_members, staff_schedules, strategic_goals\n     - suppliers, support_tickets, tax_rules, tenant_admin_alerts\n     - time_based_pricing_rules, time_entries, tip_allocations, tip_distributions\n     - training_certifications\n*/\n\n-- Add indexes for insurance_claims\nCREATE INDEX IF NOT EXISTS idx_insurance_claims_related_order_id ON public.insurance_claims(related_order_id);
\nCREATE INDEX IF NOT EXISTS idx_insurance_claims_related_restaurant_id ON public.insurance_claims(related_restaurant_id);
\n\n-- Add indexes for jobs\nCREATE INDEX IF NOT EXISTS idx_jobs_zone_id ON public.jobs(zone_id);
\n\n-- Add indexes for launch_compliance_checklist\nCREATE INDEX IF NOT EXISTS idx_launch_compliance_checklist_city_id ON public.launch_compliance_checklist(city_id);
\n\n-- Add indexes for login_sessions\nCREATE INDEX IF NOT EXISTS idx_login_sessions_driver_id ON public.login_sessions(driver_id);
\n\n-- Add indexes for loyalty_members\nCREATE INDEX IF NOT EXISTS idx_loyalty_members_restaurant_id ON public.loyalty_members(restaurant_id);
\n\n-- Add indexes for loyalty_rewards\nCREATE INDEX IF NOT EXISTS idx_loyalty_rewards_restaurant_id ON public.loyalty_rewards(restaurant_id);
\n\n-- Add indexes for loyalty_transactions\nCREATE INDEX IF NOT EXISTS idx_loyalty_transactions_member_id ON public.loyalty_transactions(member_id);
\nCREATE INDEX IF NOT EXISTS idx_loyalty_transactions_restaurant_id ON public.loyalty_transactions(restaurant_id);
\n\n-- Add indexes for maintenance_logs\nCREATE INDEX IF NOT EXISTS idx_maintenance_logs_equipment_id ON public.maintenance_logs(equipment_id);
\nCREATE INDEX IF NOT EXISTS idx_maintenance_logs_restaurant_id ON public.maintenance_logs(restaurant_id);
\n\n-- Add indexes for marketing_campaign_stats\nCREATE INDEX IF NOT EXISTS idx_marketing_campaign_stats_campaign_id ON public.marketing_campaign_stats(campaign_id);
\n\n-- Add indexes for offline_sync_queue\nCREATE INDEX IF NOT EXISTS idx_offline_sync_queue_driver_id ON public.offline_sync_queue(driver_id);
\n\n-- Add indexes for ops_alerts\nCREATE INDEX IF NOT EXISTS idx_ops_alerts_restaurant_id ON public.ops_alerts(restaurant_id);
\n\n-- Add indexes for order_status_history\nCREATE INDEX IF NOT EXISTS idx_order_status_history_order_id ON public.order_status_history(order_id);
\n\n-- Add indexes for order_timers\nCREATE INDEX IF NOT EXISTS idx_order_timers_order_id ON public.order_timers(order_id);
\n\n-- Add indexes for orders\nCREATE INDEX IF NOT EXISTS idx_orders_batch_id ON public.orders(batch_id);
\nCREATE INDEX IF NOT EXISTS idx_orders_brand_id ON public.orders(brand_id);
\nCREATE INDEX IF NOT EXISTS idx_orders_bundle_id ON public.orders(bundle_id);
\n\n-- Add indexes for p2p_bookings\nCREATE INDEX IF NOT EXISTS idx_p2p_bookings_damage_report_id ON public.p2p_bookings(damage_report_id);
\n\n-- Add indexes for p2p_dispute_resolutions\nCREATE INDEX IF NOT EXISTS idx_p2p_dispute_resolutions_damage_report_id ON public.p2p_dispute_resolutions(damage_report_id);
\n\n-- Add indexes for p2p_enhanced_claims\nCREATE INDEX IF NOT EXISTS idx_p2p_enhanced_claims_damage_report_id ON public.p2p_enhanced_claims(damage_report_id);
\n\n-- Add indexes for p2p_insurance_claims\nCREATE INDEX IF NOT EXISTS idx_p2p_insurance_claims_damage_report_id ON public.p2p_insurance_claims(damage_report_id);
\n\n-- Add indexes for p2p_payouts\nCREATE INDEX IF NOT EXISTS idx_p2p_payouts_booking_id ON public.p2p_payouts(booking_id);
\n\n-- Add indexes for p2p_protection_commissions\nCREATE INDEX IF NOT EXISTS idx_p2p_protection_commissions_protection_plan_id ON public.p2p_protection_commissions(protection_plan_id);
\n\n-- Add indexes for p2p_renter_invites\nCREATE INDEX IF NOT EXISTS idx_p2p_renter_invites_waitlist_id ON public.p2p_renter_invites(waitlist_id);
\n\n-- Add indexes for partner_portal_applications\nCREATE INDEX IF NOT EXISTS idx_partner_portal_applications_converted_to_application_id ON public.partner_portal_applications(converted_to_application_id);
\n\n-- Add indexes for payout_items\nCREATE INDEX IF NOT EXISTS idx_payout_items_payout_id ON public.payout_items(payout_id);
\n\n-- Add indexes for payout_runs\nCREATE INDEX IF NOT EXISTS idx_payout_runs_schedule_id ON public.payout_runs(schedule_id);
\n\n-- Add indexes for peak_events\nCREATE INDEX IF NOT EXISTS idx_peak_events_incentive_id ON public.peak_events(incentive_id);
\n\n-- Add indexes for performance_adjustments\nCREATE INDEX IF NOT EXISTS idx_performance_adjustments_order_id ON public.performance_adjustments(order_id);
\nCREATE INDEX IF NOT EXISTS idx_performance_adjustments_wallet_transaction_id ON public.performance_adjustments(wallet_transaction_id);
\n\n-- Add indexes for pricing_assignments\nCREATE INDEX IF NOT EXISTS idx_pricing_assignments_pricing_profile_id ON public.pricing_assignments(pricing_profile_id);
\nCREATE INDEX IF NOT EXISTS idx_pricing_assignments_zone_id ON public.pricing_assignments(zone_id);
\n\n-- Add indexes for profiles\nCREATE INDEX IF NOT EXISTS idx_profiles_loyalty_tier_id ON public.profiles(loyalty_tier_id);
\nCREATE INDEX IF NOT EXISTS idx_profiles_selected_city_id ON public.profiles(selected_city_id);
\nCREATE INDEX IF NOT EXISTS idx_profiles_zone_id ON public.profiles(zone_id);
\n\n-- Add indexes for promo_codes\nCREATE INDEX IF NOT EXISTS idx_promo_codes_segment_id ON public.promo_codes(segment_id);
\n\n-- Add indexes for promotion_usage\nCREATE INDEX IF NOT EXISTS idx_promotion_usage_food_order_id ON public.promotion_usage(food_order_id);
\nCREATE INDEX IF NOT EXISTS idx_promotion_usage_promotion_id ON public.promotion_usage(promotion_id);
\nCREATE INDEX IF NOT EXISTS idx_promotion_usage_trip_id ON public.promotion_usage(trip_id);
\n\n-- Add indexes for purchase_order_items\nCREATE INDEX IF NOT EXISTS idx_purchase_order_items_inventory_item_id ON public.purchase_order_items(inventory_item_id);
\nCREATE INDEX IF NOT EXISTS idx_purchase_order_items_purchase_order_id ON public.purchase_order_items(purchase_order_id);
\n\n-- Add indexes for purchase_orders\nCREATE INDEX IF NOT EXISTS idx_purchase_orders_restaurant_id ON public.purchase_orders(restaurant_id);
\nCREATE INDEX IF NOT EXISTS idx_purchase_orders_supplier_id ON public.purchase_orders(supplier_id);
\n\n-- Add indexes for push_campaigns\nCREATE INDEX IF NOT EXISTS idx_push_campaigns_segment_id ON public.push_campaigns(segment_id);
\n\n-- Add indexes for push_notification_logs\nCREATE INDEX IF NOT EXISTS idx_push_notification_logs_device_token_id ON public.push_notification_logs(device_token_id);
\n\n-- Add indexes for rating_flags\nCREATE INDEX IF NOT EXISTS idx_rating_flags_driver_id ON public.rating_flags(driver_id);
\n\n-- Add indexes for recipe_ingredients\nCREATE INDEX IF NOT EXISTS idx_recipe_ingredients_inventory_item_id ON public.recipe_ingredients(inventory_item_id);
\nCREATE INDEX IF NOT EXISTS idx_recipe_ingredients_recipe_id ON public.recipe_ingredients(recipe_id);
\n\n-- Add indexes for recipes\nCREATE INDEX IF NOT EXISTS idx_recipes_menu_item_id ON public.recipes(menu_item_id);
\nCREATE INDEX IF NOT EXISTS idx_recipes_restaurant_id ON public.recipes(restaurant_id);
\n\n-- Add indexes for referral_fraud_flags\nCREATE INDEX IF NOT EXISTS idx_referral_fraud_flags_referral_id ON public.referral_fraud_flags(referral_id);
\n\n-- Add indexes for region_change_logs\nCREATE INDEX IF NOT EXISTS idx_region_change_logs_new_region_id ON public.region_change_logs(new_region_id);
\nCREATE INDEX IF NOT EXISTS idx_region_change_logs_old_region_id ON public.region_change_logs(old_region_id);
\n\n-- Add indexes for reorder_rules\nCREATE INDEX IF NOT EXISTS idx_reorder_rules_preferred_supplier_id ON public.reorder_rules(preferred_supplier_id);
\n\n-- Add indexes for repositioning_alerts\nCREATE INDEX IF NOT EXISTS idx_repositioning_alerts_zone_id ON public.repositioning_alerts(zone_id);
\n\n-- Add indexes for reservations\nCREATE INDEX IF NOT EXISTS idx_reservations_restaurant_id ON public.reservations(restaurant_id);
\nCREATE INDEX IF NOT EXISTS idx_reservations_table_id ON public.reservations(table_id);
\n\n-- Add indexes for resolution_evidence\nCREATE INDEX IF NOT EXISTS idx_resolution_evidence_case_id ON public.resolution_evidence(case_id);
\n\n-- Add indexes for restaurant_branches\nCREATE INDEX IF NOT EXISTS idx_restaurant_branches_parent_restaurant_id ON public.restaurant_branches(parent_restaurant_id);
\n\n-- Add indexes for restaurant_ledger\nCREATE INDEX IF NOT EXISTS idx_restaurant_ledger_order_id ON public.restaurant_ledger(order_id);
\n\n-- Add indexes for restaurants\nCREATE INDEX IF NOT EXISTS idx_restaurants_application_id ON public.restaurants(application_id);
\nCREATE INDEX IF NOT EXISTS idx_restaurants_brand_id ON public.restaurants(brand_id);
\nCREATE INDEX IF NOT EXISTS idx_restaurants_city_id ON public.restaurants(city_id);
\nCREATE INDEX IF NOT EXISTS idx_restaurants_tenant_id ON public.restaurants(tenant_id);
\n\n-- Add indexes for restore_operations\nCREATE INDEX IF NOT EXISTS idx_restore_operations_backup_id ON public.restore_operations(backup_id);
\n\n-- Add indexes for review_reports\nCREATE INDEX IF NOT EXISTS idx_review_reports_review_id ON public.review_reports(review_id);
\n\n-- Add indexes for reward_issuances\nCREATE INDEX IF NOT EXISTS idx_reward_issuances_rule_id ON public.reward_issuances(rule_id);
\n\n-- Add indexes for reward_redemptions\nCREATE INDEX IF NOT EXISTS idx_reward_redemptions_reward_id ON public.reward_redemptions(reward_id);
\n\n-- Add indexes for ride_requests\nCREATE INDEX IF NOT EXISTS idx_ride_requests_assigned_driver_id ON public.ride_requests(assigned_driver_id);
\nCREATE INDEX IF NOT EXISTS idx_ride_requests_promo_id ON public.ride_requests(promo_id);
\n\n-- Add indexes for risk_events\nCREATE INDEX IF NOT EXISTS idx_risk_events_order_id ON public.risk_events(order_id);
\nCREATE INDEX IF NOT EXISTS idx_risk_events_tenant_id ON public.risk_events(tenant_id);
\n\n-- Add indexes for risk_scores\nCREATE INDEX IF NOT EXISTS idx_risk_scores_tenant_id ON public.risk_scores(tenant_id);
\n\n-- Add indexes for scheduled_reports\nCREATE INDEX IF NOT EXISTS idx_scheduled_reports_restaurant_id ON public.scheduled_reports(restaurant_id);
\n\n-- Add indexes for security_events\nCREATE INDEX IF NOT EXISTS idx_security_events_driver_id ON public.security_events(driver_id);
\n\n-- Add indexes for service_availability_rules\nCREATE INDEX IF NOT EXISTS idx_service_availability_rules_zone_id ON public.service_availability_rules(zone_id);
\n\n-- Add indexes for special_fees\nCREATE INDEX IF NOT EXISTS idx_special_fees_zone_id ON public.special_fees(zone_id);
\n\n-- Add indexes for staff_members\nCREATE INDEX IF NOT EXISTS idx_staff_members_restaurant_id ON public.staff_members(restaurant_id);
\n\n-- Add indexes for staff_schedules\nCREATE INDEX IF NOT EXISTS idx_staff_schedules_restaurant_id ON public.staff_schedules(restaurant_id);
\nCREATE INDEX IF NOT EXISTS idx_staff_schedules_staff_id ON public.staff_schedules(staff_id);
\n\n-- Add indexes for strategic_goals\nCREATE INDEX IF NOT EXISTS idx_strategic_goals_city_id ON public.strategic_goals(city_id);
\n\n-- Add indexes for suppliers\nCREATE INDEX IF NOT EXISTS idx_suppliers_restaurant_id ON public.suppliers(restaurant_id);
\n\n-- Add indexes for support_tickets\nCREATE INDEX IF NOT EXISTS idx_support_tickets_driver_id ON public.support_tickets(driver_id);
\nCREATE INDEX IF NOT EXISTS idx_support_tickets_food_order_id ON public.support_tickets(food_order_id);
\nCREATE INDEX IF NOT EXISTS idx_support_tickets_restaurant_id ON public.support_tickets(restaurant_id);
\nCREATE INDEX IF NOT EXISTS idx_support_tickets_tenant_id ON public.support_tickets(tenant_id);
\n\n-- Add indexes for tax_rules\nCREATE INDEX IF NOT EXISTS idx_tax_rules_city_id ON public.tax_rules(city_id);
\nCREATE INDEX IF NOT EXISTS idx_tax_rules_state_id ON public.tax_rules(state_id);
\n\n-- Add indexes for tenant_admin_alerts\nCREATE INDEX IF NOT EXISTS idx_tenant_admin_alerts_audit_log_id ON public.tenant_admin_alerts(audit_log_id);
\n\n-- Add indexes for time_based_pricing_rules\nCREATE INDEX IF NOT EXISTS idx_time_based_pricing_rules_zone_id ON public.time_based_pricing_rules(zone_id);
\n\n-- Add indexes for time_entries\nCREATE INDEX IF NOT EXISTS idx_time_entries_approved_by ON public.time_entries(approved_by);
\nCREATE INDEX IF NOT EXISTS idx_time_entries_restaurant_id ON public.time_entries(restaurant_id);
\nCREATE INDEX IF NOT EXISTS idx_time_entries_staff_id ON public.time_entries(staff_id);
\n\n-- Add indexes for tip_allocations\nCREATE INDEX IF NOT EXISTS idx_tip_allocations_distribution_id ON public.tip_allocations(distribution_id);
\nCREATE INDEX IF NOT EXISTS idx_tip_allocations_staff_id ON public.tip_allocations(staff_id);
\n\n-- Add indexes for tip_distributions\nCREATE INDEX IF NOT EXISTS idx_tip_distributions_distributed_by ON public.tip_distributions(distributed_by);
\nCREATE INDEX IF NOT EXISTS idx_tip_distributions_restaurant_id ON public.tip_distributions(restaurant_id);
\n\n-- Add indexes for training_certifications\nCREATE INDEX IF NOT EXISTS idx_training_certifications_quiz_attempt_id ON public.training_certifications(quiz_attempt_id);
;
